package com.mile.RecorderCommandService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-13T12:50:35.395-04:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", name = "RecorderCommandServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RecorderCommandServiceSoap {

    @WebMethod(operationName = "PresetSet", action = "http://videoos.net/2/XProtectCSRecorderCommand/PresetSet")
    @RequestWrapper(localName = "PresetSet", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PresetSet")
    @ResponseWrapper(localName = "PresetSetResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PresetSetResponse")
    public void presetSet(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "presetName", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String presetName
    );

    @WebMethod(operationName = "ControlLiveStream", action = "http://videoos.net/2/XProtectCSRecorderCommand/ControlLiveStream")
    @RequestWrapper(localName = "ControlLiveStream", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.ControlLiveStream")
    @ResponseWrapper(localName = "ControlLiveStreamResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.ControlLiveStreamResponse")
    public void controlLiveStream(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "clientID", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String clientID,
        @WebParam(name = "controlID", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String controlID,
        @WebParam(name = "devices", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.ArrayOfLiveStreamDevice devices
    );

    @WebMethod(operationName = "PTZMoveAbsolute", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZMoveAbsolute")
    @RequestWrapper(localName = "PTZMoveAbsolute", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZMoveAbsolute")
    @ResponseWrapper(localName = "PTZMoveAbsoluteResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZMoveAbsoluteResponse")
    public void ptzMoveAbsolute(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "ptzArgs", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.PTZArgs ptzArgs
    );

    @WebMethod(operationName = "IsManualRecording", action = "http://videoos.net/2/XProtectCSRecorderCommand/IsManualRecording")
    @RequestWrapper(localName = "IsManualRecording", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.IsManualRecording")
    @ResponseWrapper(localName = "IsManualRecordingResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.IsManualRecordingResponse")
    @WebResult(name = "IsManualRecordingResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.ArrayOfManualRecordingInfo isManualRecording(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.ArrayOfGuid deviceIds
    );

    @WebMethod(operationName = "PTZReleaseSession", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZReleaseSession")
    @RequestWrapper(localName = "PTZReleaseSession", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZReleaseSession")
    @ResponseWrapper(localName = "PTZReleaseSessionResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZReleaseSessionResponse")
    public void ptzReleaseSession(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "OutputTrigger", action = "http://videoos.net/2/XProtectCSRecorderCommand/OutputTrigger")
    @RequestWrapper(localName = "OutputTrigger", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.OutputTrigger")
    @ResponseWrapper(localName = "OutputTriggerResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.OutputTriggerResponse")
    public void outputTrigger(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "duration", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.TimeDuration duration
    );

    @WebMethod(operationName = "OutputGetState", action = "http://videoos.net/2/XProtectCSRecorderCommand/OutputGetState")
    @RequestWrapper(localName = "OutputGetState", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.OutputGetState")
    @ResponseWrapper(localName = "OutputGetStateResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.OutputGetStateResponse")
    @WebResult(name = "OutputGetStateResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.IOState outputGetState(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "PTZMoveStop", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZMoveStop")
    @RequestWrapper(localName = "PTZMoveStop", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZMoveStop")
    @ResponseWrapper(localName = "PTZMoveStopResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZMoveStopResponse")
    public void ptzMoveStop(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "SmartSearchGetResult", action = "http://videoos.net/2/XProtectCSRecorderCommand/SmartSearchGetResult")
    @RequestWrapper(localName = "SmartSearchGetResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SmartSearchGetResult")
    @ResponseWrapper(localName = "SmartSearchGetResultResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SmartSearchGetResultResponse")
    @WebResult(name = "SmartSearchGetResultResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.SmartSearchResult smartSearchGetResult(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "smartSearchId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String smartSearchId,
        @WebParam(name = "continueSearch", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        boolean continueSearch
    );

    @WebMethod(operationName = "MulticastContinue", action = "http://videoos.net/2/XProtectCSRecorderCommand/MulticastContinue")
    @RequestWrapper(localName = "MulticastContinue", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.MulticastContinue")
    @ResponseWrapper(localName = "MulticastContinueResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.MulticastContinueResponse")
    public void multicastContinue(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "multicastSessionIds", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.ArrayOfGuid multicastSessionIds
    );

    @WebMethod(operationName = "StartRecording", action = "http://videoos.net/2/XProtectCSRecorderCommand/StartRecording")
    @RequestWrapper(localName = "StartRecording", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.StartRecording")
    @ResponseWrapper(localName = "StartRecordingResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.StartRecordingResponse")
    @WebResult(name = "StartRecordingResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public boolean startRecording(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "recordingTimeMicroSeconds", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        long recordingTimeMicroSeconds
    );

    @WebMethod(operationName = "OutputActivate", action = "http://videoos.net/2/XProtectCSRecorderCommand/OutputActivate")
    @RequestWrapper(localName = "OutputActivate", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.OutputActivate")
    @ResponseWrapper(localName = "OutputActivateResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.OutputActivateResponse")
    public void outputActivate(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "JPEGGetAtOrBefore", action = "http://videoos.net/2/XProtectCSRecorderCommand/JPEGGetAtOrBefore")
    @RequestWrapper(localName = "JPEGGetAtOrBefore", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.JPEGGetAtOrBefore")
    @ResponseWrapper(localName = "JPEGGetAtOrBeforeResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.JPEGGetAtOrBeforeResponse")
    @WebResult(name = "JPEGGetAtOrBeforeResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.JPEGData jpegGetAtOrBefore(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "time", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar time
    );

    @WebMethod(operationName = "StartManualRecording", action = "http://videoos.net/2/XProtectCSRecorderCommand/StartManualRecording")
    @RequestWrapper(localName = "StartManualRecording", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.StartManualRecording")
    @ResponseWrapper(localName = "StartManualRecordingResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.StartManualRecordingResponse")
    @WebResult(name = "StartManualRecordingResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.ArrayOfManualRecordingResult startManualRecording(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.ArrayOfGuid deviceIds
    );

    @WebMethod(operationName = "StopManualRecording", action = "http://videoos.net/2/XProtectCSRecorderCommand/StopManualRecording")
    @RequestWrapper(localName = "StopManualRecording", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.StopManualRecording")
    @ResponseWrapper(localName = "StopManualRecordingResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.StopManualRecordingResponse")
    @WebResult(name = "StopManualRecordingResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.ArrayOfManualRecordingResult stopManualRecording(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.ArrayOfGuid deviceIds
    );

    @WebMethod(operationName = "PTZGetSessionInfo", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZGetSessionInfo")
    @RequestWrapper(localName = "PTZGetSessionInfo", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZGetSessionInfo")
    @ResponseWrapper(localName = "PTZGetSessionInfoResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZGetSessionInfoResponse")
    @WebResult(name = "PTZGetSessionInfoResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.PtzSessionInfo ptzGetSessionInfo(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "InputGetState", action = "http://videoos.net/2/XProtectCSRecorderCommand/InputGetState")
    @RequestWrapper(localName = "InputGetState", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.InputGetState")
    @ResponseWrapper(localName = "InputGetStateResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.InputGetStateResponse")
    @WebResult(name = "InputGetStateResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.IOState inputGetState(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "GetRetentionTimeLimit", action = "http://videoos.net/2/XProtectCSRecorderCommand/GetRetentionTimeLimit")
    @RequestWrapper(localName = "GetRetentionTimeLimit", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.GetRetentionTimeLimit")
    @ResponseWrapper(localName = "GetRetentionTimeLimitResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.GetRetentionTimeLimitResponse")
    @WebResult(name = "GetRetentionTimeLimitResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public javax.xml.datatype.XMLGregorianCalendar getRetentionTimeLimit(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "JPEGGetLive", action = "http://videoos.net/2/XProtectCSRecorderCommand/JPEGGetLive")
    @RequestWrapper(localName = "JPEGGetLive", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.JPEGGetLive")
    @ResponseWrapper(localName = "JPEGGetLiveResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.JPEGGetLiveResponse")
    @WebResult(name = "JPEGGetLiveResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.JPEGData jpegGetLive(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "maxWidth", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        int maxWidth,
        @WebParam(name = "maxHeight", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        int maxHeight
    );

    @WebMethod(operationName = "SequencesGet", action = "http://videoos.net/2/XProtectCSRecorderCommand/SequencesGet")
    @RequestWrapper(localName = "SequencesGet", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SequencesGet")
    @ResponseWrapper(localName = "SequencesGetResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SequencesGetResponse")
    @WebResult(name = "SequencesGetResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.ArrayOfSequenceEntry sequencesGet(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "sequenceType", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String sequenceType,
        @WebParam(name = "minTime", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar minTime,
        @WebParam(name = "maxTime", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar maxTime,
        @WebParam(name = "maxCount", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        int maxCount
    );

    @WebMethod(operationName = "JPEGGetAtOrAfter", action = "http://videoos.net/2/XProtectCSRecorderCommand/JPEGGetAtOrAfter")
    @RequestWrapper(localName = "JPEGGetAtOrAfter", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.JPEGGetAtOrAfter")
    @ResponseWrapper(localName = "JPEGGetAtOrAfterResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.JPEGGetAtOrAfterResponse")
    @WebResult(name = "JPEGGetAtOrAfterResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.JPEGData jpegGetAtOrAfter(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "time", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar time
    );

    @WebMethod(operationName = "PresetMoveTo", action = "http://videoos.net/2/XProtectCSRecorderCommand/PresetMoveTo")
    @RequestWrapper(localName = "PresetMoveTo", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PresetMoveTo")
    @ResponseWrapper(localName = "PresetMoveToResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PresetMoveToResponse")
    public void presetMoveTo(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "presetName", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String presetName
    );

    @WebMethod(operationName = "SendDriverCommandWithResponse", action = "http://videoos.net/2/XProtectCSRecorderCommand/SendDriverCommandWithResponse")
    @RequestWrapper(localName = "SendDriverCommandWithResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SendDriverCommandWithResponse")
    @ResponseWrapper(localName = "SendDriverCommandWithResponseResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SendDriverCommandWithResponseResponse")
    @WebResult(name = "SendDriverCommandWithResponseResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public java.lang.String sendDriverCommandWithResponse(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "command", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String command,
        @WebParam(name = "parameter", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String parameter
    );

    @WebMethod(operationName = "MulticastStop", action = "http://videoos.net/2/XProtectCSRecorderCommand/MulticastStop")
    @RequestWrapper(localName = "MulticastStop", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.MulticastStop")
    @ResponseWrapper(localName = "MulticastStopResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.MulticastStopResponse")
    public void multicastStop(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "multicastSessionIds", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.ArrayOfGuid multicastSessionIds
    );

    @WebMethod(operationName = "PTZMoveHome", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZMoveHome")
    @RequestWrapper(localName = "PTZMoveHome", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZMoveHome")
    @ResponseWrapper(localName = "PTZMoveHomeResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZMoveHomeResponse")
    public void ptzMoveHome(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "SmartSearchGetStatus", action = "http://videoos.net/2/XProtectCSRecorderCommand/SmartSearchGetStatus")
    @RequestWrapper(localName = "SmartSearchGetStatus", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SmartSearchGetStatus")
    @ResponseWrapper(localName = "SmartSearchGetStatusResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SmartSearchGetStatusResponse")
    @WebResult(name = "SmartSearchGetStatusResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.SmartSearchStatus smartSearchGetStatus(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "smartSearchId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String smartSearchId
    );

    @WebMethod(operationName = "PTZMoveStart", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZMoveStart")
    @RequestWrapper(localName = "PTZMoveStart", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZMoveStart")
    @ResponseWrapper(localName = "PTZMoveStartResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZMoveStartResponse")
    public void ptzMoveStart(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "ptzArgs", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.PTZArgs ptzArgs
    );

    @WebMethod(operationName = "PTZCenter", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZCenter")
    @RequestWrapper(localName = "PTZCenter", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZCenter")
    @ResponseWrapper(localName = "PTZCenterResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZCenterResponse")
    public void ptzCenter(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "refWidth", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double refWidth,
        @WebParam(name = "refHeight", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double refHeight,
        @WebParam(name = "centerX", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double centerX,
        @WebParam(name = "centerY", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double centerY,
        @WebParam(name = "zoom", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double zoom
    );

    @WebMethod(operationName = "TimeLineInformationGet", action = "http://videoos.net/2/XProtectCSRecorderCommand/TimeLineInformationGet")
    @RequestWrapper(localName = "TimeLineInformationGet", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.TimeLineInformationGet")
    @ResponseWrapper(localName = "TimeLineInformationGetResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.TimeLineInformationGetResponse")
    @WebResult(name = "TimeLineInformationGetResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.ArrayOfTimeLineInformationData timeLineInformationGet(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "timeLineInformationTypes", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.ArrayOfGuid timeLineInformationTypes,
        @WebParam(name = "timeLineInformationBeginTime", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar timeLineInformationBeginTime,
        @WebParam(name = "timeLineInformationInterval", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.TimeDuration timeLineInformationInterval,
        @WebParam(name = "timeLineInformationCount", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        int timeLineInformationCount
    );

    @WebMethod(operationName = "SmartSearchStart", action = "http://videoos.net/2/XProtectCSRecorderCommand/SmartSearchStart")
    @RequestWrapper(localName = "SmartSearchStart", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SmartSearchStart")
    @ResponseWrapper(localName = "SmartSearchStartResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SmartSearchStartResponse")
    @WebResult(name = "SmartSearchStartResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public java.lang.String smartSearchStart(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "searchBeginTime", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar searchBeginTime,
        @WebParam(name = "searchEndTime", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar searchEndTime,
        @WebParam(name = "sensitivity", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        int sensitivity,
        @WebParam(name = "searchInterval", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.TimeDuration searchInterval,
        @WebParam(name = "searchMask", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.ImageMask searchMask,
        @WebParam(name = "ignoreInitialMotion", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        boolean ignoreInitialMotion,
        @WebParam(name = "resultMotionMaskSize", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.Size resultMotionMaskSize
    );

    @WebMethod(operationName = "SendDriverCommand", action = "http://videoos.net/2/XProtectCSRecorderCommand/SendDriverCommand")
    @RequestWrapper(localName = "SendDriverCommand", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SendDriverCommand")
    @ResponseWrapper(localName = "SendDriverCommandResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SendDriverCommandResponse")
    public void sendDriverCommand(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "command", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String command
    );

    @WebMethod(operationName = "OutputDeactivate", action = "http://videoos.net/2/XProtectCSRecorderCommand/OutputDeactivate")
    @RequestWrapper(localName = "OutputDeactivate", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.OutputDeactivate")
    @ResponseWrapper(localName = "OutputDeactivateResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.OutputDeactivateResponse")
    public void outputDeactivate(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "PTZReserveSession", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZReserveSession")
    @RequestWrapper(localName = "PTZReserveSession", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZReserveSession")
    @ResponseWrapper(localName = "PTZReserveSessionResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZReserveSessionResponse")
    public void ptzReserveSession(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "SequencesGetAround", action = "http://videoos.net/2/XProtectCSRecorderCommand/SequencesGetAround")
    @RequestWrapper(localName = "SequencesGetAround", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SequencesGetAround")
    @ResponseWrapper(localName = "SequencesGetAroundResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SequencesGetAroundResponse")
    @WebResult(name = "SequencesGetAroundResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.ArrayOfSequenceEntry sequencesGetAround(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "sequenceType", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String sequenceType,
        @WebParam(name = "centerTime", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar centerTime,
        @WebParam(name = "maxCountBefore", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        int maxCountBefore,
        @WebParam(name = "maxCountAfter", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        int maxCountAfter
    );

    @WebMethod(operationName = "SequencesGetAroundWithSpan", action = "http://videoos.net/2/XProtectCSRecorderCommand/SequencesGetAroundWithSpan")
    @RequestWrapper(localName = "SequencesGetAroundWithSpan", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SequencesGetAroundWithSpan")
    @ResponseWrapper(localName = "SequencesGetAroundWithSpanResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SequencesGetAroundWithSpanResponse")
    @WebResult(name = "SequencesGetAroundWithSpanResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.ArrayOfSequenceEntry sequencesGetAroundWithSpan(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "sequenceType", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String sequenceType,
        @WebParam(name = "centerTime", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar centerTime,
        @WebParam(name = "maxTimeBefore", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.TimeDuration maxTimeBefore,
        @WebParam(name = "maxCountBefore", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        int maxCountBefore,
        @WebParam(name = "maxTimeAfter", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.TimeDuration maxTimeAfter,
        @WebParam(name = "maxCountAfter", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        int maxCountAfter
    );

    @WebMethod(operationName = "PTZExtendedManualSession", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZExtendedManualSession")
    @RequestWrapper(localName = "PTZExtendedManualSession", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZExtendedManualSession")
    @ResponseWrapper(localName = "PTZExtendedManualSessionResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZExtendedManualSessionResponse")
    public void ptzExtendedManualSession(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "PTZGetAbsolutePosition", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZGetAbsolutePosition")
    @RequestWrapper(localName = "PTZGetAbsolutePosition", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZGetAbsolutePosition")
    @ResponseWrapper(localName = "PTZGetAbsolutePositionResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZGetAbsolutePositionResponse")
    @WebResult(name = "PTZGetAbsolutePositionResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.PTZArgs ptzGetAbsolutePosition(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "PTZDeactivatePatrollingSchema", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZDeactivatePatrollingSchema")
    @RequestWrapper(localName = "PTZDeactivatePatrollingSchema", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZDeactivatePatrollingSchema")
    @ResponseWrapper(localName = "PTZDeactivatePatrollingSchemaResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZDeactivatePatrollingSchemaResponse")
    public void ptzDeactivatePatrollingSchema(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "patrollingSchemaId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String patrollingSchemaId
    );

    @WebMethod(operationName = "SequencesGetTypes", action = "http://videoos.net/2/XProtectCSRecorderCommand/SequencesGetTypes")
    @RequestWrapper(localName = "SequencesGetTypes", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SequencesGetTypes")
    @ResponseWrapper(localName = "SequencesGetTypesResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SequencesGetTypesResponse")
    @WebResult(name = "SequencesGetTypesResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.ArrayOfSequenceType sequencesGetTypes(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "MulticastStart", action = "http://videoos.net/2/XProtectCSRecorderCommand/MulticastStart")
    @RequestWrapper(localName = "MulticastStart", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.MulticastStart")
    @ResponseWrapper(localName = "MulticastStartResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.MulticastStartResponse")
    @WebResult(name = "MulticastStartResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.ArrayOfMulticastInfo multicastStart(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.ArrayOfGuid deviceIds,
        @WebParam(name = "clientCapabilities", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.ClientCapabilities clientCapabilities
    );

    @WebMethod(operationName = "GetVersion", action = "http://videoos.net/2/XProtectCSRecorderCommand/GetVersion")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.GetVersionResponse")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public int getVersion();

    @WebMethod(operationName = "JPEGGetAt", action = "http://videoos.net/2/XProtectCSRecorderCommand/JPEGGetAt")
    @RequestWrapper(localName = "JPEGGetAt", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.JPEGGetAt")
    @ResponseWrapper(localName = "JPEGGetAtResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.JPEGGetAtResponse")
    @WebResult(name = "JPEGGetAtResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.JPEGData jpegGetAt(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "time", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        javax.xml.datatype.XMLGregorianCalendar time
    );

    @WebMethod(operationName = "PTZActivatePatrollingSchema", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZActivatePatrollingSchema")
    @RequestWrapper(localName = "PTZActivatePatrollingSchema", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZActivatePatrollingSchema")
    @ResponseWrapper(localName = "PTZActivatePatrollingSchemaResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZActivatePatrollingSchemaResponse")
    public void ptzActivatePatrollingSchema(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "patrollingSchemaId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String patrollingSchemaId
    );

    @WebMethod(operationName = "PTZMoveRelative", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZMoveRelative")
    @RequestWrapper(localName = "PTZMoveRelative", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZMoveRelative")
    @ResponseWrapper(localName = "PTZMoveRelativeResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZMoveRelativeResponse")
    public void ptzMoveRelative(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "ptzArgs", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        com.mile.RecorderCommandService.PTZArgs ptzArgs
    );

    @WebMethod(operationName = "SmartSearchCancel", action = "http://videoos.net/2/XProtectCSRecorderCommand/SmartSearchCancel")
    @RequestWrapper(localName = "SmartSearchCancel", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SmartSearchCancel")
    @ResponseWrapper(localName = "SmartSearchCancelResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.SmartSearchCancelResponse")
    public void smartSearchCancel(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "smartSearchId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String smartSearchId
    );

    @WebMethod(operationName = "PTZRectangle", action = "http://videoos.net/2/XProtectCSRecorderCommand/PTZRectangle")
    @RequestWrapper(localName = "PTZRectangle", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZRectangle")
    @ResponseWrapper(localName = "PTZRectangleResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PTZRectangleResponse")
    public void ptzRectangle(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId,
        @WebParam(name = "refWidth", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double refWidth,
        @WebParam(name = "refHeight", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double refHeight,
        @WebParam(name = "left", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double left,
        @WebParam(name = "top", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double top,
        @WebParam(name = "bottom", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double bottom,
        @WebParam(name = "right", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        double right
    );

    @WebMethod(operationName = "PresetGetList", action = "http://videoos.net/2/XProtectCSRecorderCommand/PresetGetList")
    @RequestWrapper(localName = "PresetGetList", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PresetGetList")
    @ResponseWrapper(localName = "PresetGetListResponse", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand", className = "com.mile.RecorderCommandService.PresetGetListResponse")
    @WebResult(name = "PresetGetListResult", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
    public com.mile.RecorderCommandService.ArrayOfString presetGetList(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSRecorderCommand")
        java.lang.String deviceId
    );
}
