
package com.mile.RecorderCommandService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-13T12:50:35.053-04:00
 * Generated source version: 2.4.2
 * 
 */
public final class RecorderCommandServiceSoap_RecorderCommandServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://videoos.net/2/XProtectCSRecorderCommand", "RecorderCommandService");

    private RecorderCommandServiceSoap_RecorderCommandServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RecorderCommandService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RecorderCommandService ss = new RecorderCommandService(wsdlURL, SERVICE_NAME);
        RecorderCommandServiceSoap port = ss.getRecorderCommandServiceSoap();  
        {
        System.out.println("Invoking presetSet...");
        java.lang.String _presetSet_token = "_presetSet_token1757543392";
        java.lang.String _presetSet_deviceId = "_presetSet_deviceId-2142194876";
        java.lang.String _presetSet_presetName = "_presetSet_presetName187957489";
        port.presetSet(_presetSet_token, _presetSet_deviceId, _presetSet_presetName);


        }
        {
        System.out.println("Invoking controlLiveStream...");
        java.lang.String _controlLiveStream_token = "_controlLiveStream_token-180725078";
        java.lang.String _controlLiveStream_clientID = "_controlLiveStream_clientID1765814641";
        java.lang.String _controlLiveStream_controlID = "_controlLiveStream_controlID-923929759";
        com.mile.RecorderCommandService.ArrayOfLiveStreamDevice _controlLiveStream_devices = new com.mile.RecorderCommandService.ArrayOfLiveStreamDevice();
        java.util.List<com.mile.RecorderCommandService.LiveStreamDevice> _controlLiveStream_devicesLiveStreamDevice = new java.util.ArrayList<com.mile.RecorderCommandService.LiveStreamDevice>();
        com.mile.RecorderCommandService.LiveStreamDevice _controlLiveStream_devicesLiveStreamDeviceVal1 = new com.mile.RecorderCommandService.LiveStreamDevice();
        _controlLiveStream_devicesLiveStreamDeviceVal1.setDeviceID("DeviceID-295551966");
        com.mile.RecorderCommandService.ArrayOfLiveStreamSetting _controlLiveStream_devicesLiveStreamDeviceVal1LiveStreamSettings = new com.mile.RecorderCommandService.ArrayOfLiveStreamSetting();
        java.util.List<com.mile.RecorderCommandService.LiveStreamSetting> _controlLiveStream_devicesLiveStreamDeviceVal1LiveStreamSettingsLiveStreamSetting = new java.util.ArrayList<com.mile.RecorderCommandService.LiveStreamSetting>();
        _controlLiveStream_devicesLiveStreamDeviceVal1LiveStreamSettings.getLiveStreamSetting().addAll(_controlLiveStream_devicesLiveStreamDeviceVal1LiveStreamSettingsLiveStreamSetting);
        _controlLiveStream_devicesLiveStreamDeviceVal1.setLiveStreamSettings(_controlLiveStream_devicesLiveStreamDeviceVal1LiveStreamSettings);
        _controlLiveStream_devicesLiveStreamDevice.add(_controlLiveStream_devicesLiveStreamDeviceVal1);
        _controlLiveStream_devices.getLiveStreamDevice().addAll(_controlLiveStream_devicesLiveStreamDevice);
        port.controlLiveStream(_controlLiveStream_token, _controlLiveStream_clientID, _controlLiveStream_controlID, _controlLiveStream_devices);


        }
        {
        System.out.println("Invoking ptzMoveAbsolute...");
        java.lang.String _ptzMoveAbsolute_token = "_ptzMoveAbsolute_token-363912432";
        java.lang.String _ptzMoveAbsolute_deviceId = "_ptzMoveAbsolute_deviceId2053526942";
        com.mile.RecorderCommandService.PTZArgs _ptzMoveAbsolute_ptzArgs = new com.mile.RecorderCommandService.PTZArgs();
        java.util.List<com.mile.RecorderCommandService.PTZPairDouble> _ptzMoveAbsolute_ptzArgsMovement = new java.util.ArrayList<com.mile.RecorderCommandService.PTZPairDouble>();
        com.mile.RecorderCommandService.PTZPairDouble _ptzMoveAbsolute_ptzArgsMovementVal1 = new com.mile.RecorderCommandService.PTZPairDouble();
        _ptzMoveAbsolute_ptzArgsMovementVal1.setName("Name-1976261856");
        _ptzMoveAbsolute_ptzArgsMovementVal1.setValue(0.8276901433985754);
        _ptzMoveAbsolute_ptzArgsMovement.add(_ptzMoveAbsolute_ptzArgsMovementVal1);
        _ptzMoveAbsolute_ptzArgs.getMovement().addAll(_ptzMoveAbsolute_ptzArgsMovement);
        java.util.List<com.mile.RecorderCommandService.PTZPairDouble> _ptzMoveAbsolute_ptzArgsSpeed = new java.util.ArrayList<com.mile.RecorderCommandService.PTZPairDouble>();
        com.mile.RecorderCommandService.PTZPairDouble _ptzMoveAbsolute_ptzArgsSpeedVal1 = new com.mile.RecorderCommandService.PTZPairDouble();
        _ptzMoveAbsolute_ptzArgsSpeedVal1.setName("Name-636472146");
        _ptzMoveAbsolute_ptzArgsSpeedVal1.setValue(0.8978630544013219);
        _ptzMoveAbsolute_ptzArgsSpeed.add(_ptzMoveAbsolute_ptzArgsSpeedVal1);
        _ptzMoveAbsolute_ptzArgs.getSpeed().addAll(_ptzMoveAbsolute_ptzArgsSpeed);
        java.util.List<com.mile.RecorderCommandService.PTZPairBoolean> _ptzMoveAbsolute_ptzArgsAutomatic = new java.util.ArrayList<com.mile.RecorderCommandService.PTZPairBoolean>();
        com.mile.RecorderCommandService.PTZPairBoolean _ptzMoveAbsolute_ptzArgsAutomaticVal1 = new com.mile.RecorderCommandService.PTZPairBoolean();
        _ptzMoveAbsolute_ptzArgsAutomaticVal1.setName("Name-1114755236");
        _ptzMoveAbsolute_ptzArgsAutomaticVal1.setValue(false);
        _ptzMoveAbsolute_ptzArgsAutomatic.add(_ptzMoveAbsolute_ptzArgsAutomaticVal1);
        _ptzMoveAbsolute_ptzArgs.getAutomatic().addAll(_ptzMoveAbsolute_ptzArgsAutomatic);
        _ptzMoveAbsolute_ptzArgs.setNormalized(false);
        port.ptzMoveAbsolute(_ptzMoveAbsolute_token, _ptzMoveAbsolute_deviceId, _ptzMoveAbsolute_ptzArgs);


        }
        {
        System.out.println("Invoking isManualRecording...");
        java.lang.String _isManualRecording_token = "_isManualRecording_token-1237011474";
        com.mile.RecorderCommandService.ArrayOfGuid _isManualRecording_deviceIds = new com.mile.RecorderCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _isManualRecording_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _isManualRecording_deviceIdsGuidVal1 = "_isManualRecording_deviceIdsGuidVal1202539392";
        _isManualRecording_deviceIdsGuid.add(_isManualRecording_deviceIdsGuidVal1);
        _isManualRecording_deviceIds.getGuid().addAll(_isManualRecording_deviceIdsGuid);
        com.mile.RecorderCommandService.ArrayOfManualRecordingInfo _isManualRecording__return = port.isManualRecording(_isManualRecording_token, _isManualRecording_deviceIds);
        System.out.println("isManualRecording.result=" + _isManualRecording__return);


        }
        {
        System.out.println("Invoking ptzReleaseSession...");
        java.lang.String _ptzReleaseSession_token = "_ptzReleaseSession_token-266312416";
        java.lang.String _ptzReleaseSession_deviceId = "_ptzReleaseSession_deviceId-1612120309";
        port.ptzReleaseSession(_ptzReleaseSession_token, _ptzReleaseSession_deviceId);


        }
        {
        System.out.println("Invoking outputTrigger...");
        java.lang.String _outputTrigger_token = "_outputTrigger_token1157536297";
        java.lang.String _outputTrigger_deviceId = "_outputTrigger_deviceId1713255232";
        com.mile.RecorderCommandService.TimeDuration _outputTrigger_duration = new com.mile.RecorderCommandService.TimeDuration();
        _outputTrigger_duration.setMicroSeconds(587283400602351371l);
        port.outputTrigger(_outputTrigger_token, _outputTrigger_deviceId, _outputTrigger_duration);


        }
        {
        System.out.println("Invoking outputGetState...");
        java.lang.String _outputGetState_token = "_outputGetState_token-343371618";
        java.lang.String _outputGetState_deviceId = "_outputGetState_deviceId1995397512";
        com.mile.RecorderCommandService.IOState _outputGetState__return = port.outputGetState(_outputGetState_token, _outputGetState_deviceId);
        System.out.println("outputGetState.result=" + _outputGetState__return);


        }
        {
        System.out.println("Invoking ptzMoveStop...");
        java.lang.String _ptzMoveStop_token = "_ptzMoveStop_token996493719";
        java.lang.String _ptzMoveStop_deviceId = "_ptzMoveStop_deviceId2013716054";
        port.ptzMoveStop(_ptzMoveStop_token, _ptzMoveStop_deviceId);


        }
        {
        System.out.println("Invoking smartSearchGetResult...");
        java.lang.String _smartSearchGetResult_token = "_smartSearchGetResult_token-1294946725";
        java.lang.String _smartSearchGetResult_smartSearchId = "_smartSearchGetResult_smartSearchId298865582";
        boolean _smartSearchGetResult_continueSearch = true;
        com.mile.RecorderCommandService.SmartSearchResult _smartSearchGetResult__return = port.smartSearchGetResult(_smartSearchGetResult_token, _smartSearchGetResult_smartSearchId, _smartSearchGetResult_continueSearch);
        System.out.println("smartSearchGetResult.result=" + _smartSearchGetResult__return);


        }
        {
        System.out.println("Invoking multicastContinue...");
        java.lang.String _multicastContinue_token = "_multicastContinue_token-358234214";
        com.mile.RecorderCommandService.ArrayOfGuid _multicastContinue_multicastSessionIds = new com.mile.RecorderCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _multicastContinue_multicastSessionIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _multicastContinue_multicastSessionIdsGuidVal1 = "_multicastContinue_multicastSessionIdsGuidVal-848858154";
        _multicastContinue_multicastSessionIdsGuid.add(_multicastContinue_multicastSessionIdsGuidVal1);
        _multicastContinue_multicastSessionIds.getGuid().addAll(_multicastContinue_multicastSessionIdsGuid);
        port.multicastContinue(_multicastContinue_token, _multicastContinue_multicastSessionIds);


        }
        {
        System.out.println("Invoking startRecording...");
        java.lang.String _startRecording_token = "_startRecording_token79695555";
        java.lang.String _startRecording_deviceId = "_startRecording_deviceId1257146278";
        long _startRecording_recordingTimeMicroSeconds = 4612009978025725780l;
        boolean _startRecording__return = port.startRecording(_startRecording_token, _startRecording_deviceId, _startRecording_recordingTimeMicroSeconds);
        System.out.println("startRecording.result=" + _startRecording__return);


        }
        {
        System.out.println("Invoking outputActivate...");
        java.lang.String _outputActivate_token = "_outputActivate_token-136804821";
        java.lang.String _outputActivate_deviceId = "_outputActivate_deviceId-460343323";
        port.outputActivate(_outputActivate_token, _outputActivate_deviceId);


        }
        {
        System.out.println("Invoking jpegGetAtOrBefore...");
        java.lang.String _jpegGetAtOrBefore_token = "_jpegGetAtOrBefore_token939162387";
        java.lang.String _jpegGetAtOrBefore_deviceId = "_jpegGetAtOrBefore_deviceId1777369999";
        javax.xml.datatype.XMLGregorianCalendar _jpegGetAtOrBefore_time = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:50:35.075-04:00");
        com.mile.RecorderCommandService.JPEGData _jpegGetAtOrBefore__return = port.jpegGetAtOrBefore(_jpegGetAtOrBefore_token, _jpegGetAtOrBefore_deviceId, _jpegGetAtOrBefore_time);
        System.out.println("jpegGetAtOrBefore.result=" + _jpegGetAtOrBefore__return);


        }
        {
        System.out.println("Invoking startManualRecording...");
        java.lang.String _startManualRecording_token = "_startManualRecording_token335990640";
        com.mile.RecorderCommandService.ArrayOfGuid _startManualRecording_deviceIds = new com.mile.RecorderCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _startManualRecording_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _startManualRecording_deviceIdsGuidVal1 = "_startManualRecording_deviceIdsGuidVal-1766164445";
        _startManualRecording_deviceIdsGuid.add(_startManualRecording_deviceIdsGuidVal1);
        _startManualRecording_deviceIds.getGuid().addAll(_startManualRecording_deviceIdsGuid);
        com.mile.RecorderCommandService.ArrayOfManualRecordingResult _startManualRecording__return = port.startManualRecording(_startManualRecording_token, _startManualRecording_deviceIds);
        System.out.println("startManualRecording.result=" + _startManualRecording__return);


        }
        {
        System.out.println("Invoking stopManualRecording...");
        java.lang.String _stopManualRecording_token = "_stopManualRecording_token-1492749746";
        com.mile.RecorderCommandService.ArrayOfGuid _stopManualRecording_deviceIds = new com.mile.RecorderCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _stopManualRecording_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _stopManualRecording_deviceIdsGuidVal1 = "_stopManualRecording_deviceIdsGuidVal282776722";
        _stopManualRecording_deviceIdsGuid.add(_stopManualRecording_deviceIdsGuidVal1);
        _stopManualRecording_deviceIds.getGuid().addAll(_stopManualRecording_deviceIdsGuid);
        com.mile.RecorderCommandService.ArrayOfManualRecordingResult _stopManualRecording__return = port.stopManualRecording(_stopManualRecording_token, _stopManualRecording_deviceIds);
        System.out.println("stopManualRecording.result=" + _stopManualRecording__return);


        }
        {
        System.out.println("Invoking ptzGetSessionInfo...");
        java.lang.String _ptzGetSessionInfo_token = "_ptzGetSessionInfo_token-166228142";
        java.lang.String _ptzGetSessionInfo_deviceId = "_ptzGetSessionInfo_deviceId-1797669637";
        com.mile.RecorderCommandService.PtzSessionInfo _ptzGetSessionInfo__return = port.ptzGetSessionInfo(_ptzGetSessionInfo_token, _ptzGetSessionInfo_deviceId);
        System.out.println("ptzGetSessionInfo.result=" + _ptzGetSessionInfo__return);


        }
        {
        System.out.println("Invoking inputGetState...");
        java.lang.String _inputGetState_token = "_inputGetState_token-1705265993";
        java.lang.String _inputGetState_deviceId = "_inputGetState_deviceId-793469208";
        com.mile.RecorderCommandService.IOState _inputGetState__return = port.inputGetState(_inputGetState_token, _inputGetState_deviceId);
        System.out.println("inputGetState.result=" + _inputGetState__return);


        }
        {
        System.out.println("Invoking getRetentionTimeLimit...");
        java.lang.String _getRetentionTimeLimit_token = "_getRetentionTimeLimit_token-580047838";
        java.lang.String _getRetentionTimeLimit_deviceId = "_getRetentionTimeLimit_deviceId62376874";
        javax.xml.datatype.XMLGregorianCalendar _getRetentionTimeLimit__return = port.getRetentionTimeLimit(_getRetentionTimeLimit_token, _getRetentionTimeLimit_deviceId);
        System.out.println("getRetentionTimeLimit.result=" + _getRetentionTimeLimit__return);


        }
        {
        System.out.println("Invoking jpegGetLive...");
        java.lang.String _jpegGetLive_token = "_jpegGetLive_token-1910189536";
        java.lang.String _jpegGetLive_deviceId = "_jpegGetLive_deviceId1082277109";
        int _jpegGetLive_maxWidth = 355881295;
        int _jpegGetLive_maxHeight = 1683699738;
        com.mile.RecorderCommandService.JPEGData _jpegGetLive__return = port.jpegGetLive(_jpegGetLive_token, _jpegGetLive_deviceId, _jpegGetLive_maxWidth, _jpegGetLive_maxHeight);
        System.out.println("jpegGetLive.result=" + _jpegGetLive__return);


        }
        {
        System.out.println("Invoking sequencesGet...");
        java.lang.String _sequencesGet_token = "_sequencesGet_token494928253";
        java.lang.String _sequencesGet_deviceId = "_sequencesGet_deviceId-215032158";
        java.lang.String _sequencesGet_sequenceType = "_sequencesGet_sequenceType-1789880255";
        javax.xml.datatype.XMLGregorianCalendar _sequencesGet_minTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:50:35.090-04:00");
        javax.xml.datatype.XMLGregorianCalendar _sequencesGet_maxTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:50:35.090-04:00");
        int _sequencesGet_maxCount = 866598683;
        com.mile.RecorderCommandService.ArrayOfSequenceEntry _sequencesGet__return = port.sequencesGet(_sequencesGet_token, _sequencesGet_deviceId, _sequencesGet_sequenceType, _sequencesGet_minTime, _sequencesGet_maxTime, _sequencesGet_maxCount);
        System.out.println("sequencesGet.result=" + _sequencesGet__return);


        }
        {
        System.out.println("Invoking jpegGetAtOrAfter...");
        java.lang.String _jpegGetAtOrAfter_token = "_jpegGetAtOrAfter_token965650395";
        java.lang.String _jpegGetAtOrAfter_deviceId = "_jpegGetAtOrAfter_deviceId-581421248";
        javax.xml.datatype.XMLGregorianCalendar _jpegGetAtOrAfter_time = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:50:35.092-04:00");
        com.mile.RecorderCommandService.JPEGData _jpegGetAtOrAfter__return = port.jpegGetAtOrAfter(_jpegGetAtOrAfter_token, _jpegGetAtOrAfter_deviceId, _jpegGetAtOrAfter_time);
        System.out.println("jpegGetAtOrAfter.result=" + _jpegGetAtOrAfter__return);


        }
        {
        System.out.println("Invoking presetMoveTo...");
        java.lang.String _presetMoveTo_token = "_presetMoveTo_token1584163429";
        java.lang.String _presetMoveTo_deviceId = "_presetMoveTo_deviceId623968499";
        java.lang.String _presetMoveTo_presetName = "_presetMoveTo_presetName847370897";
        port.presetMoveTo(_presetMoveTo_token, _presetMoveTo_deviceId, _presetMoveTo_presetName);


        }
        {
        System.out.println("Invoking sendDriverCommandWithResponse...");
        java.lang.String _sendDriverCommandWithResponse_token = "_sendDriverCommandWithResponse_token-1936939611";
        java.lang.String _sendDriverCommandWithResponse_deviceId = "_sendDriverCommandWithResponse_deviceId281309320";
        java.lang.String _sendDriverCommandWithResponse_command = "_sendDriverCommandWithResponse_command-1764794344";
        java.lang.String _sendDriverCommandWithResponse_parameter = "_sendDriverCommandWithResponse_parameter-2102374220";
        java.lang.String _sendDriverCommandWithResponse__return = port.sendDriverCommandWithResponse(_sendDriverCommandWithResponse_token, _sendDriverCommandWithResponse_deviceId, _sendDriverCommandWithResponse_command, _sendDriverCommandWithResponse_parameter);
        System.out.println("sendDriverCommandWithResponse.result=" + _sendDriverCommandWithResponse__return);


        }
        {
        System.out.println("Invoking multicastStop...");
        java.lang.String _multicastStop_token = "_multicastStop_token-2055128421";
        com.mile.RecorderCommandService.ArrayOfGuid _multicastStop_multicastSessionIds = new com.mile.RecorderCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _multicastStop_multicastSessionIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _multicastStop_multicastSessionIdsGuidVal1 = "_multicastStop_multicastSessionIdsGuidVal789324649";
        _multicastStop_multicastSessionIdsGuid.add(_multicastStop_multicastSessionIdsGuidVal1);
        _multicastStop_multicastSessionIds.getGuid().addAll(_multicastStop_multicastSessionIdsGuid);
        port.multicastStop(_multicastStop_token, _multicastStop_multicastSessionIds);


        }
        {
        System.out.println("Invoking ptzMoveHome...");
        java.lang.String _ptzMoveHome_token = "_ptzMoveHome_token109283387";
        java.lang.String _ptzMoveHome_deviceId = "_ptzMoveHome_deviceId-610961457";
        port.ptzMoveHome(_ptzMoveHome_token, _ptzMoveHome_deviceId);


        }
        {
        System.out.println("Invoking smartSearchGetStatus...");
        java.lang.String _smartSearchGetStatus_token = "_smartSearchGetStatus_token657932667";
        java.lang.String _smartSearchGetStatus_smartSearchId = "_smartSearchGetStatus_smartSearchId-1117892216";
        com.mile.RecorderCommandService.SmartSearchStatus _smartSearchGetStatus__return = port.smartSearchGetStatus(_smartSearchGetStatus_token, _smartSearchGetStatus_smartSearchId);
        System.out.println("smartSearchGetStatus.result=" + _smartSearchGetStatus__return);


        }
        {
        System.out.println("Invoking ptzMoveStart...");
        java.lang.String _ptzMoveStart_token = "_ptzMoveStart_token1102340488";
        java.lang.String _ptzMoveStart_deviceId = "_ptzMoveStart_deviceId-429875245";
        com.mile.RecorderCommandService.PTZArgs _ptzMoveStart_ptzArgs = new com.mile.RecorderCommandService.PTZArgs();
        java.util.List<com.mile.RecorderCommandService.PTZPairDouble> _ptzMoveStart_ptzArgsMovement = new java.util.ArrayList<com.mile.RecorderCommandService.PTZPairDouble>();
        com.mile.RecorderCommandService.PTZPairDouble _ptzMoveStart_ptzArgsMovementVal1 = new com.mile.RecorderCommandService.PTZPairDouble();
        _ptzMoveStart_ptzArgsMovementVal1.setName("Name1717514004");
        _ptzMoveStart_ptzArgsMovementVal1.setValue(0.8717907818262242);
        _ptzMoveStart_ptzArgsMovement.add(_ptzMoveStart_ptzArgsMovementVal1);
        _ptzMoveStart_ptzArgs.getMovement().addAll(_ptzMoveStart_ptzArgsMovement);
        java.util.List<com.mile.RecorderCommandService.PTZPairDouble> _ptzMoveStart_ptzArgsSpeed = new java.util.ArrayList<com.mile.RecorderCommandService.PTZPairDouble>();
        com.mile.RecorderCommandService.PTZPairDouble _ptzMoveStart_ptzArgsSpeedVal1 = new com.mile.RecorderCommandService.PTZPairDouble();
        _ptzMoveStart_ptzArgsSpeedVal1.setName("Name683045452");
        _ptzMoveStart_ptzArgsSpeedVal1.setValue(0.0029465479762490476);
        _ptzMoveStart_ptzArgsSpeed.add(_ptzMoveStart_ptzArgsSpeedVal1);
        _ptzMoveStart_ptzArgs.getSpeed().addAll(_ptzMoveStart_ptzArgsSpeed);
        java.util.List<com.mile.RecorderCommandService.PTZPairBoolean> _ptzMoveStart_ptzArgsAutomatic = new java.util.ArrayList<com.mile.RecorderCommandService.PTZPairBoolean>();
        com.mile.RecorderCommandService.PTZPairBoolean _ptzMoveStart_ptzArgsAutomaticVal1 = new com.mile.RecorderCommandService.PTZPairBoolean();
        _ptzMoveStart_ptzArgsAutomaticVal1.setName("Name-582615017");
        _ptzMoveStart_ptzArgsAutomaticVal1.setValue(true);
        _ptzMoveStart_ptzArgsAutomatic.add(_ptzMoveStart_ptzArgsAutomaticVal1);
        _ptzMoveStart_ptzArgs.getAutomatic().addAll(_ptzMoveStart_ptzArgsAutomatic);
        _ptzMoveStart_ptzArgs.setNormalized(false);
        port.ptzMoveStart(_ptzMoveStart_token, _ptzMoveStart_deviceId, _ptzMoveStart_ptzArgs);


        }
        {
        System.out.println("Invoking ptzCenter...");
        java.lang.String _ptzCenter_token = "_ptzCenter_token571716724";
        java.lang.String _ptzCenter_deviceId = "_ptzCenter_deviceId-1532670718";
        double _ptzCenter_refWidth = 0.11900656292538325;
        double _ptzCenter_refHeight = 0.3526624536728976;
        double _ptzCenter_centerX = 0.340993542020814;
        double _ptzCenter_centerY = 5.372500332269103E-4;
        double _ptzCenter_zoom = 0.35687687458306827;
        port.ptzCenter(_ptzCenter_token, _ptzCenter_deviceId, _ptzCenter_refWidth, _ptzCenter_refHeight, _ptzCenter_centerX, _ptzCenter_centerY, _ptzCenter_zoom);


        }
        {
        System.out.println("Invoking timeLineInformationGet...");
        java.lang.String _timeLineInformationGet_token = "_timeLineInformationGet_token-573186974";
        java.lang.String _timeLineInformationGet_deviceId = "_timeLineInformationGet_deviceId1147503376";
        com.mile.RecorderCommandService.ArrayOfGuid _timeLineInformationGet_timeLineInformationTypes = new com.mile.RecorderCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _timeLineInformationGet_timeLineInformationTypesGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _timeLineInformationGet_timeLineInformationTypesGuidVal1 = "_timeLineInformationGet_timeLineInformationTypesGuidVal-2047121351";
        _timeLineInformationGet_timeLineInformationTypesGuid.add(_timeLineInformationGet_timeLineInformationTypesGuidVal1);
        _timeLineInformationGet_timeLineInformationTypes.getGuid().addAll(_timeLineInformationGet_timeLineInformationTypesGuid);
        javax.xml.datatype.XMLGregorianCalendar _timeLineInformationGet_timeLineInformationBeginTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:50:35.120-04:00");
        com.mile.RecorderCommandService.TimeDuration _timeLineInformationGet_timeLineInformationInterval = new com.mile.RecorderCommandService.TimeDuration();
        _timeLineInformationGet_timeLineInformationInterval.setMicroSeconds(-5763073160269744721l);
        int _timeLineInformationGet_timeLineInformationCount = -1130116248;
        com.mile.RecorderCommandService.ArrayOfTimeLineInformationData _timeLineInformationGet__return = port.timeLineInformationGet(_timeLineInformationGet_token, _timeLineInformationGet_deviceId, _timeLineInformationGet_timeLineInformationTypes, _timeLineInformationGet_timeLineInformationBeginTime, _timeLineInformationGet_timeLineInformationInterval, _timeLineInformationGet_timeLineInformationCount);
        System.out.println("timeLineInformationGet.result=" + _timeLineInformationGet__return);


        }
        {
        System.out.println("Invoking smartSearchStart...");
        java.lang.String _smartSearchStart_token = "_smartSearchStart_token862802558";
        java.lang.String _smartSearchStart_deviceId = "_smartSearchStart_deviceId-1357152196";
        javax.xml.datatype.XMLGregorianCalendar _smartSearchStart_searchBeginTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:50:35.123-04:00");
        javax.xml.datatype.XMLGregorianCalendar _smartSearchStart_searchEndTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:50:35.123-04:00");
        int _smartSearchStart_sensitivity = -179941905;
        com.mile.RecorderCommandService.TimeDuration _smartSearchStart_searchInterval = new com.mile.RecorderCommandService.TimeDuration();
        _smartSearchStart_searchInterval.setMicroSeconds(-6366266723080730984l);
        com.mile.RecorderCommandService.ImageMask _smartSearchStart_searchMask = new com.mile.RecorderCommandService.ImageMask();
        com.mile.RecorderCommandService.Size _smartSearchStart_searchMaskSize = new com.mile.RecorderCommandService.Size();
        _smartSearchStart_searchMaskSize.setWidth(1036851251);
        _smartSearchStart_searchMaskSize.setHeight(-1176191975);
        _smartSearchStart_searchMask.setSize(_smartSearchStart_searchMaskSize);
        _smartSearchStart_searchMask.setMask("Mask-748102650");
        boolean _smartSearchStart_ignoreInitialMotion = true;
        com.mile.RecorderCommandService.Size _smartSearchStart_resultMotionMaskSize = new com.mile.RecorderCommandService.Size();
        _smartSearchStart_resultMotionMaskSize.setWidth(-445798736);
        _smartSearchStart_resultMotionMaskSize.setHeight(163071983);
        java.lang.String _smartSearchStart__return = port.smartSearchStart(_smartSearchStart_token, _smartSearchStart_deviceId, _smartSearchStart_searchBeginTime, _smartSearchStart_searchEndTime, _smartSearchStart_sensitivity, _smartSearchStart_searchInterval, _smartSearchStart_searchMask, _smartSearchStart_ignoreInitialMotion, _smartSearchStart_resultMotionMaskSize);
        System.out.println("smartSearchStart.result=" + _smartSearchStart__return);


        }
        {
        System.out.println("Invoking sendDriverCommand...");
        java.lang.String _sendDriverCommand_token = "_sendDriverCommand_token456158381";
        java.lang.String _sendDriverCommand_deviceId = "_sendDriverCommand_deviceId-341314604";
        java.lang.String _sendDriverCommand_command = "_sendDriverCommand_command-1691697891";
        port.sendDriverCommand(_sendDriverCommand_token, _sendDriverCommand_deviceId, _sendDriverCommand_command);


        }
        {
        System.out.println("Invoking outputDeactivate...");
        java.lang.String _outputDeactivate_token = "_outputDeactivate_token2123997590";
        java.lang.String _outputDeactivate_deviceId = "_outputDeactivate_deviceId-1399752538";
        port.outputDeactivate(_outputDeactivate_token, _outputDeactivate_deviceId);


        }
        {
        System.out.println("Invoking ptzReserveSession...");
        java.lang.String _ptzReserveSession_token = "_ptzReserveSession_token1009838628";
        java.lang.String _ptzReserveSession_deviceId = "_ptzReserveSession_deviceId-825839961";
        port.ptzReserveSession(_ptzReserveSession_token, _ptzReserveSession_deviceId);


        }
        {
        System.out.println("Invoking sequencesGetAround...");
        java.lang.String _sequencesGetAround_token = "_sequencesGetAround_token-597721496";
        java.lang.String _sequencesGetAround_deviceId = "_sequencesGetAround_deviceId160258984";
        java.lang.String _sequencesGetAround_sequenceType = "_sequencesGetAround_sequenceType-681159858";
        javax.xml.datatype.XMLGregorianCalendar _sequencesGetAround_centerTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:50:35.130-04:00");
        int _sequencesGetAround_maxCountBefore = -1594965471;
        int _sequencesGetAround_maxCountAfter = 1519693577;
        com.mile.RecorderCommandService.ArrayOfSequenceEntry _sequencesGetAround__return = port.sequencesGetAround(_sequencesGetAround_token, _sequencesGetAround_deviceId, _sequencesGetAround_sequenceType, _sequencesGetAround_centerTime, _sequencesGetAround_maxCountBefore, _sequencesGetAround_maxCountAfter);
        System.out.println("sequencesGetAround.result=" + _sequencesGetAround__return);


        }
        {
        System.out.println("Invoking sequencesGetAroundWithSpan...");
        java.lang.String _sequencesGetAroundWithSpan_token = "_sequencesGetAroundWithSpan_token-1252008167";
        java.lang.String _sequencesGetAroundWithSpan_deviceId = "_sequencesGetAroundWithSpan_deviceId1486201085";
        java.lang.String _sequencesGetAroundWithSpan_sequenceType = "_sequencesGetAroundWithSpan_sequenceType178789928";
        javax.xml.datatype.XMLGregorianCalendar _sequencesGetAroundWithSpan_centerTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:50:35.135-04:00");
        com.mile.RecorderCommandService.TimeDuration _sequencesGetAroundWithSpan_maxTimeBefore = new com.mile.RecorderCommandService.TimeDuration();
        _sequencesGetAroundWithSpan_maxTimeBefore.setMicroSeconds(3688732561219353815l);
        int _sequencesGetAroundWithSpan_maxCountBefore = -1481975845;
        com.mile.RecorderCommandService.TimeDuration _sequencesGetAroundWithSpan_maxTimeAfter = new com.mile.RecorderCommandService.TimeDuration();
        _sequencesGetAroundWithSpan_maxTimeAfter.setMicroSeconds(4133411129821793255l);
        int _sequencesGetAroundWithSpan_maxCountAfter = -102987211;
        com.mile.RecorderCommandService.ArrayOfSequenceEntry _sequencesGetAroundWithSpan__return = port.sequencesGetAroundWithSpan(_sequencesGetAroundWithSpan_token, _sequencesGetAroundWithSpan_deviceId, _sequencesGetAroundWithSpan_sequenceType, _sequencesGetAroundWithSpan_centerTime, _sequencesGetAroundWithSpan_maxTimeBefore, _sequencesGetAroundWithSpan_maxCountBefore, _sequencesGetAroundWithSpan_maxTimeAfter, _sequencesGetAroundWithSpan_maxCountAfter);
        System.out.println("sequencesGetAroundWithSpan.result=" + _sequencesGetAroundWithSpan__return);


        }
        {
        System.out.println("Invoking ptzExtendedManualSession...");
        java.lang.String _ptzExtendedManualSession_token = "_ptzExtendedManualSession_token1178957894";
        java.lang.String _ptzExtendedManualSession_deviceId = "_ptzExtendedManualSession_deviceId-943412773";
        port.ptzExtendedManualSession(_ptzExtendedManualSession_token, _ptzExtendedManualSession_deviceId);


        }
        {
        System.out.println("Invoking ptzGetAbsolutePosition...");
        java.lang.String _ptzGetAbsolutePosition_token = "_ptzGetAbsolutePosition_token858397196";
        java.lang.String _ptzGetAbsolutePosition_deviceId = "_ptzGetAbsolutePosition_deviceId-69234877";
        com.mile.RecorderCommandService.PTZArgs _ptzGetAbsolutePosition__return = port.ptzGetAbsolutePosition(_ptzGetAbsolutePosition_token, _ptzGetAbsolutePosition_deviceId);
        System.out.println("ptzGetAbsolutePosition.result=" + _ptzGetAbsolutePosition__return);


        }
        {
        System.out.println("Invoking ptzDeactivatePatrollingSchema...");
        java.lang.String _ptzDeactivatePatrollingSchema_token = "_ptzDeactivatePatrollingSchema_token-614023613";
        java.lang.String _ptzDeactivatePatrollingSchema_deviceId = "_ptzDeactivatePatrollingSchema_deviceId1367052922";
        java.lang.String _ptzDeactivatePatrollingSchema_patrollingSchemaId = "_ptzDeactivatePatrollingSchema_patrollingSchemaId1324285113";
        port.ptzDeactivatePatrollingSchema(_ptzDeactivatePatrollingSchema_token, _ptzDeactivatePatrollingSchema_deviceId, _ptzDeactivatePatrollingSchema_patrollingSchemaId);


        }
        {
        System.out.println("Invoking sequencesGetTypes...");
        java.lang.String _sequencesGetTypes_token = "_sequencesGetTypes_token1796689490";
        java.lang.String _sequencesGetTypes_deviceId = "_sequencesGetTypes_deviceId-1917883214";
        com.mile.RecorderCommandService.ArrayOfSequenceType _sequencesGetTypes__return = port.sequencesGetTypes(_sequencesGetTypes_token, _sequencesGetTypes_deviceId);
        System.out.println("sequencesGetTypes.result=" + _sequencesGetTypes__return);


        }
        {
        System.out.println("Invoking multicastStart...");
        java.lang.String _multicastStart_token = "_multicastStart_token-808327792";
        com.mile.RecorderCommandService.ArrayOfGuid _multicastStart_deviceIds = new com.mile.RecorderCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _multicastStart_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _multicastStart_deviceIdsGuidVal1 = "_multicastStart_deviceIdsGuidVal-2094308374";
        _multicastStart_deviceIdsGuid.add(_multicastStart_deviceIdsGuidVal1);
        _multicastStart_deviceIds.getGuid().addAll(_multicastStart_deviceIdsGuid);
        com.mile.RecorderCommandService.ClientCapabilities _multicastStart_clientCapabilities = new com.mile.RecorderCommandService.ClientCapabilities();
        _multicastStart_clientCapabilities.setPrivacyMask(true);
        com.mile.RecorderCommandService.ArrayOfMulticastInfo _multicastStart__return = port.multicastStart(_multicastStart_token, _multicastStart_deviceIds, _multicastStart_clientCapabilities);
        System.out.println("multicastStart.result=" + _multicastStart__return);


        }
        {
        System.out.println("Invoking getVersion...");
        int _getVersion__return = port.getVersion();
        System.out.println("getVersion.result=" + _getVersion__return);


        }
        {
        System.out.println("Invoking jpegGetAt...");
        java.lang.String _jpegGetAt_token = "_jpegGetAt_token148019139";
        java.lang.String _jpegGetAt_deviceId = "_jpegGetAt_deviceId1216400779";
        javax.xml.datatype.XMLGregorianCalendar _jpegGetAt_time = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:50:35.145-04:00");
        com.mile.RecorderCommandService.JPEGData _jpegGetAt__return = port.jpegGetAt(_jpegGetAt_token, _jpegGetAt_deviceId, _jpegGetAt_time);
        System.out.println("jpegGetAt.result=" + _jpegGetAt__return);


        }
        {
        System.out.println("Invoking ptzActivatePatrollingSchema...");
        java.lang.String _ptzActivatePatrollingSchema_token = "_ptzActivatePatrollingSchema_token-1434979939";
        java.lang.String _ptzActivatePatrollingSchema_deviceId = "_ptzActivatePatrollingSchema_deviceId-54557235";
        java.lang.String _ptzActivatePatrollingSchema_patrollingSchemaId = "_ptzActivatePatrollingSchema_patrollingSchemaId726016680";
        port.ptzActivatePatrollingSchema(_ptzActivatePatrollingSchema_token, _ptzActivatePatrollingSchema_deviceId, _ptzActivatePatrollingSchema_patrollingSchemaId);


        }
        {
        System.out.println("Invoking ptzMoveRelative...");
        java.lang.String _ptzMoveRelative_token = "_ptzMoveRelative_token1286571192";
        java.lang.String _ptzMoveRelative_deviceId = "_ptzMoveRelative_deviceId-140357464";
        com.mile.RecorderCommandService.PTZArgs _ptzMoveRelative_ptzArgs = new com.mile.RecorderCommandService.PTZArgs();
        java.util.List<com.mile.RecorderCommandService.PTZPairDouble> _ptzMoveRelative_ptzArgsMovement = new java.util.ArrayList<com.mile.RecorderCommandService.PTZPairDouble>();
        com.mile.RecorderCommandService.PTZPairDouble _ptzMoveRelative_ptzArgsMovementVal1 = new com.mile.RecorderCommandService.PTZPairDouble();
        _ptzMoveRelative_ptzArgsMovementVal1.setName("Name216767808");
        _ptzMoveRelative_ptzArgsMovementVal1.setValue(0.3303358879848669);
        _ptzMoveRelative_ptzArgsMovement.add(_ptzMoveRelative_ptzArgsMovementVal1);
        _ptzMoveRelative_ptzArgs.getMovement().addAll(_ptzMoveRelative_ptzArgsMovement);
        java.util.List<com.mile.RecorderCommandService.PTZPairDouble> _ptzMoveRelative_ptzArgsSpeed = new java.util.ArrayList<com.mile.RecorderCommandService.PTZPairDouble>();
        com.mile.RecorderCommandService.PTZPairDouble _ptzMoveRelative_ptzArgsSpeedVal1 = new com.mile.RecorderCommandService.PTZPairDouble();
        _ptzMoveRelative_ptzArgsSpeedVal1.setName("Name-1934891834");
        _ptzMoveRelative_ptzArgsSpeedVal1.setValue(0.9058426375344559);
        _ptzMoveRelative_ptzArgsSpeed.add(_ptzMoveRelative_ptzArgsSpeedVal1);
        _ptzMoveRelative_ptzArgs.getSpeed().addAll(_ptzMoveRelative_ptzArgsSpeed);
        java.util.List<com.mile.RecorderCommandService.PTZPairBoolean> _ptzMoveRelative_ptzArgsAutomatic = new java.util.ArrayList<com.mile.RecorderCommandService.PTZPairBoolean>();
        com.mile.RecorderCommandService.PTZPairBoolean _ptzMoveRelative_ptzArgsAutomaticVal1 = new com.mile.RecorderCommandService.PTZPairBoolean();
        _ptzMoveRelative_ptzArgsAutomaticVal1.setName("Name1711680234");
        _ptzMoveRelative_ptzArgsAutomaticVal1.setValue(true);
        _ptzMoveRelative_ptzArgsAutomatic.add(_ptzMoveRelative_ptzArgsAutomaticVal1);
        _ptzMoveRelative_ptzArgs.getAutomatic().addAll(_ptzMoveRelative_ptzArgsAutomatic);
        _ptzMoveRelative_ptzArgs.setNormalized(true);
        port.ptzMoveRelative(_ptzMoveRelative_token, _ptzMoveRelative_deviceId, _ptzMoveRelative_ptzArgs);


        }
        {
        System.out.println("Invoking smartSearchCancel...");
        java.lang.String _smartSearchCancel_token = "_smartSearchCancel_token530153025";
        java.lang.String _smartSearchCancel_smartSearchId = "_smartSearchCancel_smartSearchId-2136795077";
        port.smartSearchCancel(_smartSearchCancel_token, _smartSearchCancel_smartSearchId);


        }
        {
        System.out.println("Invoking ptzRectangle...");
        java.lang.String _ptzRectangle_token = "_ptzRectangle_token-940603144";
        java.lang.String _ptzRectangle_deviceId = "_ptzRectangle_deviceId-1997155992";
        double _ptzRectangle_refWidth = 0.3716894663375111;
        double _ptzRectangle_refHeight = 0.1565532254041263;
        double _ptzRectangle_left = 0.5555392799063877;
        double _ptzRectangle_top = 0.606304649221024;
        double _ptzRectangle_bottom = 0.2407180026629291;
        double _ptzRectangle_right = 0.621810935479384;
        port.ptzRectangle(_ptzRectangle_token, _ptzRectangle_deviceId, _ptzRectangle_refWidth, _ptzRectangle_refHeight, _ptzRectangle_left, _ptzRectangle_top, _ptzRectangle_bottom, _ptzRectangle_right);


        }
        {
        System.out.println("Invoking presetGetList...");
        java.lang.String _presetGetList_token = "_presetGetList_token-911872693";
        java.lang.String _presetGetList_deviceId = "_presetGetList_deviceId-2122742040";
        com.mile.RecorderCommandService.ArrayOfString _presetGetList__return = port.presetGetList(_presetGetList_token, _presetGetList_deviceId);
        System.out.println("presetGetList.result=" + _presetGetList__return);


        }

        System.exit(0);
    }

}
