package com.mile.RecorderStatusService2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-13T13:01:06.081-04:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RecorderStatusService2", 
                  wsdlLocation = "file:/C:/Program Files/Milestone/MIPSDK/WSDL/RecorderStatusService2.wsdl",
                  targetNamespace = "http://videoos.net/2/XProtectCSRecorderStatus2") 
public class RecorderStatusService2 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://videoos.net/2/XProtectCSRecorderStatus2", "RecorderStatusService2");
    public final static QName RecorderStatusService2Soap = new QName("http://videoos.net/2/XProtectCSRecorderStatus2", "RecorderStatusService2Soap");
    public final static QName RecorderStatusService2Soap12 = new QName("http://videoos.net/2/XProtectCSRecorderStatus2", "RecorderStatusService2Soap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Program Files/Milestone/MIPSDK/WSDL/RecorderStatusService2.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecorderStatusService2.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Program Files/Milestone/MIPSDK/WSDL/RecorderStatusService2.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecorderStatusService2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecorderStatusService2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecorderStatusService2() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecorderStatusService2(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecorderStatusService2(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecorderStatusService2(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RecorderStatusService2Soap
     */
    @WebEndpoint(name = "RecorderStatusService2Soap")
    public RecorderStatusService2Soap getRecorderStatusService2Soap() {
        return super.getPort(RecorderStatusService2Soap, RecorderStatusService2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecorderStatusService2Soap
     */
    @WebEndpoint(name = "RecorderStatusService2Soap")
    public RecorderStatusService2Soap getRecorderStatusService2Soap(WebServiceFeature... features) {
        return super.getPort(RecorderStatusService2Soap, RecorderStatusService2Soap.class, features);
    }
    /**
     *
     * @return
     *     returns RecorderStatusService2Soap
     */
    @WebEndpoint(name = "RecorderStatusService2Soap12")
    public RecorderStatusService2Soap getRecorderStatusService2Soap12() {
        return super.getPort(RecorderStatusService2Soap12, RecorderStatusService2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecorderStatusService2Soap
     */
    @WebEndpoint(name = "RecorderStatusService2Soap12")
    public RecorderStatusService2Soap getRecorderStatusService2Soap12(WebServiceFeature... features) {
        return super.getPort(RecorderStatusService2Soap12, RecorderStatusService2Soap.class, features);
    }

}
