
package com.mile.RecorderStatusService2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-13T13:01:05.807-04:00
 * Generated source version: 2.4.2
 * 
 */
public final class RecorderStatusService2Soap_RecorderStatusService2Soap12_Client {

    private static final QName SERVICE_NAME = new QName("http://videoos.net/2/XProtectCSRecorderStatus2", "RecorderStatusService2");

    private RecorderStatusService2Soap_RecorderStatusService2Soap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RecorderStatusService2.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RecorderStatusService2 ss = new RecorderStatusService2(wsdlURL, SERVICE_NAME);
        RecorderStatusService2Soap port = ss.getRecorderStatusService2Soap12();  
        
        {
        System.out.println("Invoking subscribeDeviceStatus...");
        java.lang.String _subscribeDeviceStatus_token = "_subscribeDeviceStatus_token-2038596312";
        java.lang.String _subscribeDeviceStatus_statusSessionId = "_subscribeDeviceStatus_statusSessionId779672455";
        com.mile.RecorderStatusService2.ArrayOfGuid _subscribeDeviceStatus_deviceIds = new com.mile.RecorderStatusService2.ArrayOfGuid();
        java.util.List<java.lang.String> _subscribeDeviceStatus_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _subscribeDeviceStatus_deviceIdsGuidVal1 = "_subscribeDeviceStatus_deviceIdsGuidVal-728823132";
        _subscribeDeviceStatus_deviceIdsGuid.add(_subscribeDeviceStatus_deviceIdsGuidVal1);
        _subscribeDeviceStatus_deviceIds.getGuid().addAll(_subscribeDeviceStatus_deviceIdsGuid);
        port.subscribeDeviceStatus(_subscribeDeviceStatus_token, _subscribeDeviceStatus_statusSessionId, _subscribeDeviceStatus_deviceIds);


        }
        {
        System.out.println("Invoking stopStatusSession...");
        java.lang.String _stopStatusSession_token = "_stopStatusSession_token-2025746370";
        java.lang.String _stopStatusSession_statusSessionId = "_stopStatusSession_statusSessionId701593380";
        port.stopStatusSession(_stopStatusSession_token, _stopStatusSession_statusSessionId);


        }
        {
        System.out.println("Invoking getArchiveStorageStatus...");
        java.lang.String _getArchiveStorageStatus_token = "_getArchiveStorageStatus_token-14568135";
        com.mile.RecorderStatusService2.ArrayOfStorageStatus _getArchiveStorageStatus__return = port.getArchiveStorageStatus(_getArchiveStorageStatus_token);
        System.out.println("getArchiveStorageStatus.result=" + _getArchiveStorageStatus__return);


        }
        {
        System.out.println("Invoking subscribeEventStatus...");
        java.lang.String _subscribeEventStatus_token = "_subscribeEventStatus_token265854008";
        java.lang.String _subscribeEventStatus_statusSessionId = "_subscribeEventStatus_statusSessionId1108731956";
        com.mile.RecorderStatusService2.ArrayOfGuid _subscribeEventStatus_eventIds = new com.mile.RecorderStatusService2.ArrayOfGuid();
        java.util.List<java.lang.String> _subscribeEventStatus_eventIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _subscribeEventStatus_eventIdsGuidVal1 = "_subscribeEventStatus_eventIdsGuidVal-1562035464";
        _subscribeEventStatus_eventIdsGuid.add(_subscribeEventStatus_eventIdsGuidVal1);
        _subscribeEventStatus_eventIds.getGuid().addAll(_subscribeEventStatus_eventIdsGuid);
        port.subscribeEventStatus(_subscribeEventStatus_token, _subscribeEventStatus_statusSessionId, _subscribeEventStatus_eventIds);


        }
        {
        System.out.println("Invoking getVersion...");
        int _getVersion__return = port.getVersion();
        System.out.println("getVersion.result=" + _getVersion__return);


        }
        {
        System.out.println("Invoking getCurrentDeviceStatus...");
        java.lang.String _getCurrentDeviceStatus_token = "_getCurrentDeviceStatus_token-858364437";
        com.mile.RecorderStatusService2.ArrayOfGuid _getCurrentDeviceStatus_deviceIds = new com.mile.RecorderStatusService2.ArrayOfGuid();
        java.util.List<java.lang.String> _getCurrentDeviceStatus_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getCurrentDeviceStatus_deviceIdsGuidVal1 = "_getCurrentDeviceStatus_deviceIdsGuidVal1448083426";
        _getCurrentDeviceStatus_deviceIdsGuid.add(_getCurrentDeviceStatus_deviceIdsGuidVal1);
        _getCurrentDeviceStatus_deviceIds.getGuid().addAll(_getCurrentDeviceStatus_deviceIdsGuid);
        com.mile.RecorderStatusService2.Status _getCurrentDeviceStatus__return = port.getCurrentDeviceStatus(_getCurrentDeviceStatus_token, _getCurrentDeviceStatus_deviceIds);
        System.out.println("getCurrentDeviceStatus.result=" + _getCurrentDeviceStatus__return);


        }
        {
        System.out.println("Invoking getVideoDeviceStatistics...");
        java.lang.String _getVideoDeviceStatistics_token = "_getVideoDeviceStatistics_token-1651959348";
        com.mile.RecorderStatusService2.ArrayOfGuid _getVideoDeviceStatistics_deviceIds = new com.mile.RecorderStatusService2.ArrayOfGuid();
        java.util.List<java.lang.String> _getVideoDeviceStatistics_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getVideoDeviceStatistics_deviceIdsGuidVal1 = "_getVideoDeviceStatistics_deviceIdsGuidVal1462791601";
        _getVideoDeviceStatistics_deviceIdsGuid.add(_getVideoDeviceStatistics_deviceIdsGuidVal1);
        _getVideoDeviceStatistics_deviceIds.getGuid().addAll(_getVideoDeviceStatistics_deviceIdsGuid);
        com.mile.RecorderStatusService2.ArrayOfVideoDeviceStatistics _getVideoDeviceStatistics__return = port.getVideoDeviceStatistics(_getVideoDeviceStatistics_token, _getVideoDeviceStatistics_deviceIds);
        System.out.println("getVideoDeviceStatistics.result=" + _getVideoDeviceStatistics__return);


        }
        {
        System.out.println("Invoking startStatusSession...");
        java.lang.String _startStatusSession_token = "_startStatusSession_token-539811193";
        java.lang.String _startStatusSession__return = port.startStatusSession(_startStatusSession_token);
        System.out.println("startStatusSession.result=" + _startStatusSession__return);


        }
        {
        System.out.println("Invoking getStatus...");
        java.lang.String _getStatus_token = "_getStatus_token603710703";
        java.lang.String _getStatus_statusSessionId = "_getStatus_statusSessionId25269231";
        int _getStatus_millisecondsTimeout = -983082465;
        com.mile.RecorderStatusService2.Status _getStatus__return = port.getStatus(_getStatus_token, _getStatus_statusSessionId, _getStatus_millisecondsTimeout);
        System.out.println("getStatus.result=" + _getStatus__return);


        }
        {
        System.out.println("Invoking getRecordingStorageStatus...");
        java.lang.String _getRecordingStorageStatus_token = "_getRecordingStorageStatus_token-58718710";
        com.mile.RecorderStatusService2.ArrayOfStorageStatus _getRecordingStorageStatus__return = port.getRecordingStorageStatus(_getRecordingStorageStatus_token);
        System.out.println("getRecordingStorageStatus.result=" + _getRecordingStorageStatus__return);


        }
        {
        System.out.println("Invoking subscribeConfigurationStatus...");
        java.lang.String _subscribeConfigurationStatus_token = "_subscribeConfigurationStatus_token-741039451";
        java.lang.String _subscribeConfigurationStatus_statusSessionId = "_subscribeConfigurationStatus_statusSessionId2040248903";
        boolean _subscribeConfigurationStatus_subscribe = false;
        port.subscribeConfigurationStatus(_subscribeConfigurationStatus_token, _subscribeConfigurationStatus_statusSessionId, _subscribeConfigurationStatus_subscribe);


        }
        {
        System.out.println("Invoking getRecorderStatus...");
        com.mile.RecorderStatusService2.AttachAndConnectionState _getRecorderStatus__return = port.getRecorderStatus();
        System.out.println("getRecorderStatus.result=" + _getRecorderStatus__return);


        }
        {
        System.out.println("Invoking getAudioDeviceStatistics...");
        java.lang.String _getAudioDeviceStatistics_token = "_getAudioDeviceStatistics_token-772924623";
        com.mile.RecorderStatusService2.ArrayOfGuid _getAudioDeviceStatistics_deviceIds = new com.mile.RecorderStatusService2.ArrayOfGuid();
        java.util.List<java.lang.String> _getAudioDeviceStatistics_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getAudioDeviceStatistics_deviceIdsGuidVal1 = "_getAudioDeviceStatistics_deviceIdsGuidVal195629553";
        _getAudioDeviceStatistics_deviceIdsGuid.add(_getAudioDeviceStatistics_deviceIdsGuidVal1);
        _getAudioDeviceStatistics_deviceIds.getGuid().addAll(_getAudioDeviceStatistics_deviceIdsGuid);
        com.mile.RecorderStatusService2.ArrayOfAudioDeviceStatistics _getAudioDeviceStatistics__return = port.getAudioDeviceStatistics(_getAudioDeviceStatistics_token, _getAudioDeviceStatistics_deviceIds);
        System.out.println("getAudioDeviceStatistics.result=" + _getAudioDeviceStatistics__return);


        }

        System.exit(0);
    }

}
