package com.mile.ServiceRegistrationService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-13T12:59:44.003-04:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", name = "ServiceRegistrationServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceRegistrationServiceSoap {

    @WebMethod(operationName = "GetServices", action = "http://videoos.net/2/XProtectCSServiceRegistration/GetServices")
    @RequestWrapper(localName = "GetServices", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.GetServices")
    @ResponseWrapper(localName = "GetServicesResponse", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.GetServicesResponse")
    @WebResult(name = "GetServicesResult", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
    public com.mile.ServiceRegistrationService.ArrayOfServiceInfo getServices();

    @WebMethod(operationName = "UnregisterService", action = "http://videoos.net/2/XProtectCSServiceRegistration/UnregisterService")
    @RequestWrapper(localName = "UnregisterService", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.UnregisterService")
    @ResponseWrapper(localName = "UnregisterServiceResponse", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.UnregisterServiceResponse")
    public void unregisterService(
        @WebParam(name = "instance", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        java.lang.String instance
    );

    @WebMethod(operationName = "GetServiceData", action = "http://videoos.net/2/XProtectCSServiceRegistration/GetServiceData")
    @RequestWrapper(localName = "GetServiceData", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.GetServiceData")
    @ResponseWrapper(localName = "GetServiceDataResponse", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.GetServiceDataResponse")
    @WebResult(name = "GetServiceDataResult", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
    public java.lang.String getServiceData(
        @WebParam(name = "instance", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        java.lang.String instance
    );

    @WebMethod(operationName = "EnableService", action = "http://videoos.net/2/XProtectCSServiceRegistration/EnableService")
    @RequestWrapper(localName = "EnableService", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.EnableService")
    @ResponseWrapper(localName = "EnableServiceResponse", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.EnableServiceResponse")
    public void enableService(
        @WebParam(name = "instance", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        java.lang.String instance,
        @WebParam(name = "enabled", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        boolean enabled
    );

    @WebMethod(operationName = "GetServicesIncludingDisabled", action = "http://videoos.net/2/XProtectCSServiceRegistration/GetServicesIncludingDisabled")
    @RequestWrapper(localName = "GetServicesIncludingDisabled", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.GetServicesIncludingDisabled")
    @ResponseWrapper(localName = "GetServicesIncludingDisabledResponse", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.GetServicesIncludingDisabledResponse")
    @WebResult(name = "GetServicesIncludingDisabledResult", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
    public com.mile.ServiceRegistrationService.ArrayOfServiceInfo getServicesIncludingDisabled();

    @WebMethod(operationName = "SetServiceData", action = "http://videoos.net/2/XProtectCSServiceRegistration/SetServiceData")
    @RequestWrapper(localName = "SetServiceData", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.SetServiceData")
    @ResponseWrapper(localName = "SetServiceDataResponse", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.SetServiceDataResponse")
    @WebResult(name = "SetServiceDataResult", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
    public boolean setServiceData(
        @WebParam(name = "instance", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        java.lang.String instance,
        @WebParam(name = "customData", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        java.lang.String customData
    );

    @WebMethod(operationName = "RegisterService", action = "http://videoos.net/2/XProtectCSServiceRegistration/RegisterService")
    @RequestWrapper(localName = "RegisterService", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.RegisterService")
    @ResponseWrapper(localName = "RegisterServiceResponse", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration", className = "com.mile.ServiceRegistrationService.RegisterServiceResponse")
    @WebResult(name = "RegisterServiceResult", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
    public boolean registerService(
        @WebParam(name = "type", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        java.lang.String type,
        @WebParam(name = "instance", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        java.lang.String instance,
        @WebParam(name = "uri", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        com.mile.ServiceRegistrationService.ArrayOfString uri,
        @WebParam(name = "name", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        java.lang.String description,
        @WebParam(name = "customData", targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration")
        java.lang.String customData
    );
}
