
package com.mile.ServiceRegistrationService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-13T12:59:43.850-04:00
 * Generated source version: 2.4.2
 * 
 */
public final class ServiceRegistrationServiceSoap_ServiceRegistrationServiceSoap1_Client {

    private static final QName SERVICE_NAME = new QName("http://videoos.net/2/XProtectCSServiceRegistration", "ServiceRegistrationService");

    private ServiceRegistrationServiceSoap_ServiceRegistrationServiceSoap1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServiceRegistrationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServiceRegistrationService ss = new ServiceRegistrationService(wsdlURL, SERVICE_NAME);
        ServiceRegistrationServiceSoap port = ss.getServiceRegistrationServiceSoap1();  
        
        {
        System.out.println("Invoking getServices...");
        com.mile.ServiceRegistrationService.ArrayOfServiceInfo _getServices__return = port.getServices();
        System.out.println("getServices.result=" + _getServices__return);


        }
        {
        System.out.println("Invoking unregisterService...");
        java.lang.String _unregisterService_instance = "_unregisterService_instance1688293213";
        port.unregisterService(_unregisterService_instance);


        }
        {
        System.out.println("Invoking getServiceData...");
        java.lang.String _getServiceData_instance = "_getServiceData_instance13696556";
        java.lang.String _getServiceData__return = port.getServiceData(_getServiceData_instance);
        System.out.println("getServiceData.result=" + _getServiceData__return);


        }
        {
        System.out.println("Invoking enableService...");
        java.lang.String _enableService_instance = "_enableService_instance1493054288";
        boolean _enableService_enabled = true;
        port.enableService(_enableService_instance, _enableService_enabled);


        }
        {
        System.out.println("Invoking getServicesIncludingDisabled...");
        com.mile.ServiceRegistrationService.ArrayOfServiceInfo _getServicesIncludingDisabled__return = port.getServicesIncludingDisabled();
        System.out.println("getServicesIncludingDisabled.result=" + _getServicesIncludingDisabled__return);


        }
        {
        System.out.println("Invoking setServiceData...");
        java.lang.String _setServiceData_instance = "_setServiceData_instance2059810656";
        java.lang.String _setServiceData_customData = "_setServiceData_customData-959967274";
        boolean _setServiceData__return = port.setServiceData(_setServiceData_instance, _setServiceData_customData);
        System.out.println("setServiceData.result=" + _setServiceData__return);


        }
        {
        System.out.println("Invoking registerService...");
        java.lang.String _registerService_type = "_registerService_type-611000445";
        java.lang.String _registerService_instance = "_registerService_instance-588428172";
        com.mile.ServiceRegistrationService.ArrayOfString _registerService_uri = new com.mile.ServiceRegistrationService.ArrayOfString();
        java.util.List<java.lang.String> _registerService_uriString = new java.util.ArrayList<java.lang.String>();
        java.lang.String _registerService_uriStringVal1 = "_registerService_uriStringVal1678275300";
        _registerService_uriString.add(_registerService_uriStringVal1);
        _registerService_uri.getString().addAll(_registerService_uriString);
        java.lang.String _registerService_name = "_registerService_name1166818937";
        java.lang.String _registerService_description = "_registerService_description-1252608552";
        java.lang.String _registerService_customData = "_registerService_customData-293209723";
        boolean _registerService__return = port.registerService(_registerService_type, _registerService_instance, _registerService_uri, _registerService_name, _registerService_description, _registerService_customData);
        System.out.println("registerService.result=" + _registerService__return);


        }

        System.exit(0);
    }

}
