package com.mile.ServiceRegistrationService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-13T12:59:44.034-04:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ServiceRegistrationService", 
                  wsdlLocation = "file:/C:/Program Files/Milestone/MIPSDK/WSDL/ServiceRegistrationService.wsdl",
                  targetNamespace = "http://videoos.net/2/XProtectCSServiceRegistration") 
public class ServiceRegistrationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://videoos.net/2/XProtectCSServiceRegistration", "ServiceRegistrationService");
    public final static QName ServiceRegistrationServiceSoap = new QName("http://videoos.net/2/XProtectCSServiceRegistration", "ServiceRegistrationServiceSoap");
    public final static QName ServiceRegistrationServiceSoap1 = new QName("http://videoos.net/2/XProtectCSServiceRegistration", "ServiceRegistrationServiceSoap1");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Program Files/Milestone/MIPSDK/WSDL/ServiceRegistrationService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceRegistrationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Program Files/Milestone/MIPSDK/WSDL/ServiceRegistrationService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceRegistrationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceRegistrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceRegistrationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceRegistrationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceRegistrationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceRegistrationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServiceRegistrationServiceSoap
     */
    @WebEndpoint(name = "ServiceRegistrationServiceSoap")
    public ServiceRegistrationServiceSoap getServiceRegistrationServiceSoap() {
        return super.getPort(ServiceRegistrationServiceSoap, ServiceRegistrationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceRegistrationServiceSoap
     */
    @WebEndpoint(name = "ServiceRegistrationServiceSoap")
    public ServiceRegistrationServiceSoap getServiceRegistrationServiceSoap(WebServiceFeature... features) {
        return super.getPort(ServiceRegistrationServiceSoap, ServiceRegistrationServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ServiceRegistrationServiceSoap
     */
    @WebEndpoint(name = "ServiceRegistrationServiceSoap1")
    public ServiceRegistrationServiceSoap getServiceRegistrationServiceSoap1() {
        return super.getPort(ServiceRegistrationServiceSoap1, ServiceRegistrationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceRegistrationServiceSoap
     */
    @WebEndpoint(name = "ServiceRegistrationServiceSoap1")
    public ServiceRegistrationServiceSoap getServiceRegistrationServiceSoap1(WebServiceFeature... features) {
        return super.getPort(ServiceRegistrationServiceSoap1, ServiceRegistrationServiceSoap.class, features);
    }

}
