package com.mile.ServerCommandService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-13T12:46:28.028-04:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", name = "ServerCommandServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServerCommandServiceSoap {

    @WebMethod(operationName = "SetCustomSettingDataGlobal", action = "http://videoos.net/2/XProtectCSServerCommand/SetCustomSettingDataGlobal")
    @RequestWrapper(localName = "SetCustomSettingDataGlobal", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.SetCustomSettingDataGlobal")
    @ResponseWrapper(localName = "SetCustomSettingDataGlobalResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.SetCustomSettingDataGlobalResponse")
    @WebResult(name = "SetCustomSettingDataGlobalResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.SetCustomSettingResultType setCustomSettingDataGlobal(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId,
        @WebParam(name = "customSettingData", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.CustomSettingData customSettingData,
        @WebParam(name = "forceOverride", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        boolean forceOverride
    );

    @WebMethod(operationName = "SetCustomSettingDataUser", action = "http://videoos.net/2/XProtectCSServerCommand/SetCustomSettingDataUser")
    @RequestWrapper(localName = "SetCustomSettingDataUser", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.SetCustomSettingDataUser")
    @ResponseWrapper(localName = "SetCustomSettingDataUserResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.SetCustomSettingDataUserResponse")
    @WebResult(name = "SetCustomSettingDataUserResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.SetCustomSettingResultType setCustomSettingDataUser(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId,
        @WebParam(name = "customSettingData", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.CustomSettingData customSettingData,
        @WebParam(name = "forceOverride", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        boolean forceOverride
    );

    @WebMethod(operationName = "GetServerVersion", action = "http://videoos.net/2/XProtectCSServerCommand/GetServerVersion")
    @RequestWrapper(localName = "GetServerVersion", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetServerVersion")
    @ResponseWrapper(localName = "GetServerVersionResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetServerVersionResponse")
    @WebResult(name = "GetServerVersionResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public java.lang.String getServerVersion();

    @WebMethod(operationName = "GetViewGroupData", action = "http://videoos.net/2/XProtectCSServerCommand/GetViewGroupData")
    @RequestWrapper(localName = "GetViewGroupData", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetViewGroupData")
    @ResponseWrapper(localName = "GetViewGroupDataResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetViewGroupDataResponse")
    @WebResult(name = "GetViewGroupDataResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ViewGroup getViewGroupData(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "viewGroupId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String viewGroupId
    );

    @WebMethod(operationName = "MarkedDataCreate", action = "http://videoos.net/2/XProtectCSServerCommand/MarkedDataCreate")
    @RequestWrapper(localName = "MarkedDataCreate", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataCreate")
    @ResponseWrapper(localName = "MarkedDataCreateResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataCreateResponse")
    @WebResult(name = "MarkedDataCreateResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.MarkedDataResult markedDataCreate(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "markedDataId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String markedDataId,
        @WebParam(name = "deviceIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid deviceIds,
        @WebParam(name = "timeStart", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeStart,
        @WebParam(name = "timeTag", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeTag,
        @WebParam(name = "timeEnd", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeEnd,
        @WebParam(name = "reference", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String reference,
        @WebParam(name = "header", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String header,
        @WebParam(name = "description", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String description,
        @WebParam(name = "markedDataType", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        int markedDataType,
        @WebParam(name = "useRetention", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        boolean useRetention,
        @WebParam(name = "retentionExpire", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar retentionExpire,
        @WebParam(name = "retentionOption", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.RetentionOption retentionOption
    );

    @WebMethod(operationName = "MatrixMonitorActivateCamera", action = "http://videoos.net/2/XProtectCSServerCommand/MatrixMonitorActivateCamera")
    @RequestWrapper(localName = "MatrixMonitorActivateCamera", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MatrixMonitorActivateCamera")
    @ResponseWrapper(localName = "MatrixMonitorActivateCameraResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MatrixMonitorActivateCameraResponse")
    public void matrixMonitorActivateCamera(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "matrixMonitorId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String matrixMonitorId,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "UpdatePresetPosition", action = "http://videoos.net/2/XProtectCSServerCommand/UpdatePresetPosition")
    @RequestWrapper(localName = "UpdatePresetPosition", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.UpdatePresetPosition")
    @ResponseWrapper(localName = "UpdatePresetPositionResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.UpdatePresetPositionResponse")
    public void updatePresetPosition(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "id", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String id,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "GetCustomSettingDataUser", action = "http://videoos.net/2/XProtectCSServerCommand/GetCustomSettingDataUser")
    @RequestWrapper(localName = "GetCustomSettingDataUser", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetCustomSettingDataUser")
    @ResponseWrapper(localName = "GetCustomSettingDataUserResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetCustomSettingDataUserResponse")
    @WebResult(name = "GetCustomSettingDataUserResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.CustomSetting getCustomSettingDataUser(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId
    );

    @WebMethod(operationName = "GetVersion", action = "http://videoos.net/2/XProtectCSServerCommand/GetVersion")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetVersionResponse")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public int getVersion();

    @WebMethod(operationName = "Logout", action = "http://videoos.net/2/XProtectCSServerCommand/Logout")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.LogoutResponse")
    public void logout(
        @WebParam(name = "instanceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String instanceId,
        @WebParam(name = "currentToken", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String currentToken
    );

    @WebMethod(operationName = "MarkedDataSearch", action = "http://videoos.net/2/XProtectCSServerCommand/MarkedDataSearch")
    @RequestWrapper(localName = "MarkedDataSearch", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataSearch")
    @ResponseWrapper(localName = "MarkedDataSearchResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataSearchResponse")
    @WebResult(name = "MarkedDataSearchResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfMarkedData markedDataSearch(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid deviceIds,
        @WebParam(name = "searchText", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String searchText,
        @WebParam(name = "users", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfString users,
        @WebParam(name = "createdFromTime", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar createdFromTime,
        @WebParam(name = "createdToTime", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar createdToTime,
        @WebParam(name = "markedDataFromTime", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar markedDataFromTime,
        @WebParam(name = "markedDataToTime", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar markedDataToTime,
        @WebParam(name = "tagTimeFromTime", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar tagTimeFromTime,
        @WebParam(name = "tagTimeToTime", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar tagTimeToTime,
        @WebParam(name = "retentionExpireFrom", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar retentionExpireFrom,
        @WebParam(name = "retentionExpireTo", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar retentionExpireTo,
        @WebParam(name = "pageIndex", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        int pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        int pageSize,
        @WebParam(name = "sortOrder", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.SortOrderOption sortOrder,
        @WebParam(name = "sortAscending", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        boolean sortAscending
    );

    @WebMethod(operationName = "BookmarkCreate", action = "http://videoos.net/2/XProtectCSServerCommand/BookmarkCreate")
    @RequestWrapper(localName = "BookmarkCreate", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkCreate")
    @ResponseWrapper(localName = "BookmarkCreateResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkCreateResponse")
    @WebResult(name = "BookmarkCreateResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.Bookmark bookmarkCreate(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "timeBegin", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeBegin,
        @WebParam(name = "timeTrigged", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeTrigged,
        @WebParam(name = "timeEnd", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeEnd,
        @WebParam(name = "reference", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String reference,
        @WebParam(name = "header", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String header,
        @WebParam(name = "description", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String description
    );

    @WebMethod(operationName = "GetVmoServicesList", action = "http://videoos.net/2/XProtectCSServerCommand/GetVmoServicesList")
    @RequestWrapper(localName = "GetVmoServicesList", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetVmoServicesList")
    @ResponseWrapper(localName = "GetVmoServicesListResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetVmoServicesListResponse")
    @WebResult(name = "GetVmoServicesListResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfDictionaryEntry getVmoServicesList();

    @WebMethod(operationName = "MarkedDataUpdate", action = "http://videoos.net/2/XProtectCSServerCommand/MarkedDataUpdate")
    @RequestWrapper(localName = "MarkedDataUpdate", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataUpdate")
    @ResponseWrapper(localName = "MarkedDataUpdateResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataUpdateResponse")
    @WebResult(name = "MarkedDataUpdateResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.MarkedDataResult markedDataUpdate(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "markedDataId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String markedDataId,
        @WebParam(name = "deviceIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid deviceIds,
        @WebParam(name = "timeStart", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeStart,
        @WebParam(name = "timeTag", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeTag,
        @WebParam(name = "timeEnd", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeEnd,
        @WebParam(name = "reference", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String reference,
        @WebParam(name = "header", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String header,
        @WebParam(name = "description", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String description,
        @WebParam(name = "markedDataType", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        int markedDataType,
        @WebParam(name = "useRetention", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        boolean useRetention,
        @WebParam(name = "retentionExpire", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar retentionExpire,
        @WebParam(name = "retentionOption", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.RetentionOption retentionOption
    );

    @WebMethod(operationName = "CheckSmartClientVersion", action = "http://videoos.net/2/XProtectCSServerCommand/CheckSmartClientVersion")
    @RequestWrapper(localName = "CheckSmartClientVersion", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.CheckSmartClientVersion")
    @ResponseWrapper(localName = "CheckSmartClientVersionResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.CheckSmartClientVersionResponse")
    @WebResult(name = "CheckSmartClientVersionResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.SmartClientVersion checkSmartClientVersion(
        @WebParam(name = "major", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        int major,
        @WebParam(name = "minor", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        int minor,
        @WebParam(name = "revision", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String revision
    );

    @WebMethod(operationName = "GetConfigurationHardware", action = "http://videoos.net/2/XProtectCSServerCommand/GetConfigurationHardware")
    @RequestWrapper(localName = "GetConfigurationHardware", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetConfigurationHardware")
    @ResponseWrapper(localName = "GetConfigurationHardwareResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetConfigurationHardwareResponse")
    @WebResult(name = "GetConfigurationHardwareResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfHardwareInfo getConfigurationHardware(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "hardwareIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid hardwareIds
    );

    @WebMethod(operationName = "GetViewGroups", action = "http://videoos.net/2/XProtectCSServerCommand/GetViewGroups")
    @RequestWrapper(localName = "GetViewGroups", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetViewGroups")
    @ResponseWrapper(localName = "GetViewGroupsResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetViewGroupsResponse")
    @WebResult(name = "GetViewGroupsResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfViewGroupInfo getViewGroups(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token
    );

    @WebMethod(operationName = "BookmarkGetNewReference", action = "http://videoos.net/2/XProtectCSServerCommand/BookmarkGetNewReference")
    @RequestWrapper(localName = "BookmarkGetNewReference", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkGetNewReference")
    @ResponseWrapper(localName = "BookmarkGetNewReferenceResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkGetNewReferenceResponse")
    @WebResult(name = "BookmarkGetNewReferenceResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.BookmarkReference bookmarkGetNewReference(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "live", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        boolean live
    );

    @WebMethod(operationName = "GetPresets", action = "http://videoos.net/2/XProtectCSServerCommand/GetPresets")
    @RequestWrapper(localName = "GetPresets", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetPresets")
    @ResponseWrapper(localName = "GetPresetsResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetPresetsResponse")
    @WebResult(name = "GetPresetsResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfPresetInfo getPresets(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String deviceId
    );

    @WebMethod(operationName = "BookmarkSearchTime", action = "http://videoos.net/2/XProtectCSServerCommand/BookmarkSearchTime")
    @RequestWrapper(localName = "BookmarkSearchTime", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkSearchTime")
    @ResponseWrapper(localName = "BookmarkSearchTimeResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkSearchTimeResponse")
    @WebResult(name = "BookmarkSearchTimeResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfBookmark bookmarkSearchTime(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "time", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar time,
        @WebParam(name = "timeLimit", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.TimeDuration timeLimit,
        @WebParam(name = "countLimit", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        int countLimit,
        @WebParam(name = "deviceTypes", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfMediaDeviceType deviceTypes,
        @WebParam(name = "optDeviceIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid optDeviceIds,
        @WebParam(name = "optUsers", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfString optUsers,
        @WebParam(name = "optSearchStr", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String optSearchStr
    );

    @WebMethod(operationName = "MarkedDataGetNewReference", action = "http://videoos.net/2/XProtectCSServerCommand/MarkedDataGetNewReference")
    @RequestWrapper(localName = "MarkedDataGetNewReference", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataGetNewReference")
    @ResponseWrapper(localName = "MarkedDataGetNewReferenceResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataGetNewReferenceResponse")
    @WebResult(name = "MarkedDataGetNewReferenceResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.MarkedDataReference markedDataGetNewReference(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid deviceIds,
        @WebParam(name = "live", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        boolean live
    );

    @WebMethod(operationName = "GetClientProfile", action = "http://videoos.net/2/XProtectCSServerCommand/GetClientProfile")
    @RequestWrapper(localName = "GetClientProfile", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetClientProfile")
    @ResponseWrapper(localName = "GetClientProfileResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetClientProfileResponse")
    @WebResult(name = "GetClientProfileResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ClientProfile getClientProfile(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "withSetting", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        boolean withSetting
    );

    @WebMethod(operationName = "BookmarkUpdate", action = "http://videoos.net/2/XProtectCSServerCommand/BookmarkUpdate")
    @RequestWrapper(localName = "BookmarkUpdate", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkUpdate")
    @ResponseWrapper(localName = "BookmarkUpdateResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkUpdateResponse")
    @WebResult(name = "BookmarkUpdateResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.Bookmark bookmarkUpdate(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "bookmarkId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String bookmarkId,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "timeBegin", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeBegin,
        @WebParam(name = "timeTrigged", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeTrigged,
        @WebParam(name = "timeEnd", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar timeEnd,
        @WebParam(name = "reference", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String reference,
        @WebParam(name = "header", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String header,
        @WebParam(name = "description", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String description
    );

    @WebMethod(operationName = "GetProductInfo", action = "http://videoos.net/2/XProtectCSServerCommand/GetProductInfo")
    @RequestWrapper(localName = "GetProductInfo", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetProductInfo")
    @ResponseWrapper(localName = "GetProductInfoResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetProductInfoResponse")
    @WebResult(name = "GetProductInfoResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ProductInfo getProductInfo();

    @WebMethod(operationName = "CreatePreset", action = "http://videoos.net/2/XProtectCSServerCommand/CreatePreset")
    @RequestWrapper(localName = "CreatePreset", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.CreatePreset")
    @ResponseWrapper(localName = "CreatePresetResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.CreatePresetResponse")
    @WebResult(name = "CreatePresetResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public java.lang.String createPreset(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "name", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String name
    );

    @WebMethod(operationName = "IsOnline", action = "http://videoos.net/2/XProtectCSServerCommand/IsOnline")
    @RequestWrapper(localName = "IsOnline", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.IsOnline")
    @ResponseWrapper(localName = "IsOnlineResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.IsOnlineResponse")
    @WebResult(name = "IsOnlineResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public boolean isOnline();

    @WebMethod(operationName = "QueryRecorderInfo", action = "http://videoos.net/2/XProtectCSServerCommand/QueryRecorderInfo")
    @RequestWrapper(localName = "QueryRecorderInfo", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.QueryRecorderInfo")
    @ResponseWrapper(localName = "QueryRecorderInfoResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.QueryRecorderInfoResponse")
    @WebResult(name = "QueryRecorderInfoResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.RecorderInfo queryRecorderInfo(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "recorderId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String recorderId
    );

    @WebMethod(operationName = "GetCustomSettingDataGlobal", action = "http://videoos.net/2/XProtectCSServerCommand/GetCustomSettingDataGlobal")
    @RequestWrapper(localName = "GetCustomSettingDataGlobal", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetCustomSettingDataGlobal")
    @ResponseWrapper(localName = "GetCustomSettingDataGlobalResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetCustomSettingDataGlobalResponse")
    @WebResult(name = "GetCustomSettingDataGlobalResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.CustomSetting getCustomSettingDataGlobal(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "customSettingId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String customSettingId
    );

    @WebMethod(operationName = "GetConfigurationRecorders", action = "http://videoos.net/2/XProtectCSServerCommand/GetConfigurationRecorders")
    @RequestWrapper(localName = "GetConfigurationRecorders", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetConfigurationRecorders")
    @ResponseWrapper(localName = "GetConfigurationRecordersResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetConfigurationRecordersResponse")
    @WebResult(name = "GetConfigurationRecordersResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfRecorderInfo getConfigurationRecorders(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "recorderIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid recorderIds
    );

    @WebMethod(operationName = "GetSystemLicenseInfo", action = "http://videoos.net/2/XProtectCSServerCommand/GetSystemLicenseInfo")
    @RequestWrapper(localName = "GetSystemLicenseInfo", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetSystemLicenseInfo")
    @ResponseWrapper(localName = "GetSystemLicenseInfoResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetSystemLicenseInfoResponse")
    @WebResult(name = "GetSystemLicenseInfoResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.SystemLicenseInfo getSystemLicenseInfo();

    @WebMethod(operationName = "AlertsGetAroundWithSpan", action = "http://videoos.net/2/XProtectCSServerCommand/AlertsGetAroundWithSpan")
    @RequestWrapper(localName = "AlertsGetAroundWithSpan", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.AlertsGetAroundWithSpan")
    @ResponseWrapper(localName = "AlertsGetAroundWithSpanResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.AlertsGetAroundWithSpanResponse")
    @WebResult(name = "AlertsGetAroundWithSpanResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfAlertOccurrence alertsGetAroundWithSpan(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "alertIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid alertIds,
        @WebParam(name = "centerTime", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar centerTime,
        @WebParam(name = "maxTimeBefore", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.TimeDuration maxTimeBefore,
        @WebParam(name = "maxCountBefore", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        int maxCountBefore,
        @WebParam(name = "maxTimeAfter", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.TimeDuration maxTimeAfter,
        @WebParam(name = "maxCountAfter", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        int maxCountAfter
    );

    @WebMethod(operationName = "QueryChanges", action = "http://videoos.net/2/XProtectCSServerCommand/QueryChanges")
    @RequestWrapper(localName = "QueryChanges", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.QueryChanges")
    @ResponseWrapper(localName = "QueryChangesResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.QueryChangesResponse")
    @WebResult(name = "QueryChangesResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfChange queryChanges(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "changesFrom", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        javax.xml.datatype.XMLGregorianCalendar changesFrom
    );

    @WebMethod(operationName = "QuerySystemMonitorStateSourcesByIds", action = "http://videoos.net/2/XProtectCSServerCommand/QuerySystemMonitorStateSourcesByIds")
    @RequestWrapper(localName = "QuerySystemMonitorStateSourcesByIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.QuerySystemMonitorStateSourcesByIds")
    @ResponseWrapper(localName = "QuerySystemMonitorStateSourcesByIdsResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.QuerySystemMonitorStateSourcesByIdsResponse")
    @WebResult(name = "QuerySystemMonitorStateSourcesByIdsResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfSystemMonitorStateSource querySystemMonitorStateSourcesByIds(
        @WebParam(name = "ids", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfString ids
    );

    @WebMethod(operationName = "EventTrigger", action = "http://videoos.net/2/XProtectCSServerCommand/EventTrigger")
    @RequestWrapper(localName = "EventTrigger", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.EventTrigger")
    @ResponseWrapper(localName = "EventTriggerResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.EventTriggerResponse")
    public void eventTrigger(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "eventId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String eventId
    );

    @WebMethod(operationName = "BookmarkSearchFromBookmark", action = "http://videoos.net/2/XProtectCSServerCommand/BookmarkSearchFromBookmark")
    @RequestWrapper(localName = "BookmarkSearchFromBookmark", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkSearchFromBookmark")
    @ResponseWrapper(localName = "BookmarkSearchFromBookmarkResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkSearchFromBookmarkResponse")
    @WebResult(name = "BookmarkSearchFromBookmarkResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfBookmark bookmarkSearchFromBookmark(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "fromBookmarkId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String fromBookmarkId,
        @WebParam(name = "timeLimit", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.TimeDuration timeLimit,
        @WebParam(name = "countLimit", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        int countLimit,
        @WebParam(name = "deviceTypes", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfMediaDeviceType deviceTypes,
        @WebParam(name = "optDeviceIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid optDeviceIds,
        @WebParam(name = "optUsers", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfString optUsers,
        @WebParam(name = "optSearchStr", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String optSearchStr
    );

    @WebMethod(operationName = "MarkedDataDelete", action = "http://videoos.net/2/XProtectCSServerCommand/MarkedDataDelete")
    @RequestWrapper(localName = "MarkedDataDelete", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataDelete")
    @ResponseWrapper(localName = "MarkedDataDeleteResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataDeleteResponse")
    @WebResult(name = "MarkedDataDeleteResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfMarkedDataResult markedDataDelete(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "markedDataIds", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid markedDataIds
    );

    @WebMethod(operationName = "MarkedDataGet", action = "http://videoos.net/2/XProtectCSServerCommand/MarkedDataGet")
    @RequestWrapper(localName = "MarkedDataGet", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataGet")
    @ResponseWrapper(localName = "MarkedDataGetResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.MarkedDataGetResponse")
    @WebResult(name = "MarkedDataGetResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.MarkedData markedDataGet(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "markedDataId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String markedDataId
    );

    @WebMethod(operationName = "Login", action = "http://videoos.net/2/XProtectCSServerCommand/Login")
    @RequestWrapper(localName = "Login", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.LoginResponse")
    @WebResult(name = "LoginResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.LoginInfo login(
        @WebParam(name = "instanceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String instanceId,
        @WebParam(name = "currentToken", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String currentToken
    );

    @WebMethod(operationName = "GetSmartClientVersion", action = "http://videoos.net/2/XProtectCSServerCommand/GetSmartClientVersion")
    @RequestWrapper(localName = "GetSmartClientVersion", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetSmartClientVersion")
    @ResponseWrapper(localName = "GetSmartClientVersionResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetSmartClientVersionResponse")
    @WebResult(name = "GetSmartClientVersionResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.SmartClientVersion getSmartClientVersion();

    @WebMethod(operationName = "UpdatePresetName", action = "http://videoos.net/2/XProtectCSServerCommand/UpdatePresetName")
    @RequestWrapper(localName = "UpdatePresetName", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.UpdatePresetName")
    @ResponseWrapper(localName = "UpdatePresetNameResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.UpdatePresetNameResponse")
    public void updatePresetName(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "id", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String id,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "newName", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String newName
    );

    @WebMethod(operationName = "EventTriggerWithMetadata", action = "http://videoos.net/2/XProtectCSServerCommand/EventTriggerWithMetadata")
    @RequestWrapper(localName = "EventTriggerWithMetadata", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.EventTriggerWithMetadata")
    @ResponseWrapper(localName = "EventTriggerWithMetadataResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.EventTriggerWithMetadataResponse")
    public void eventTriggerWithMetadata(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "eventId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String eventId,
        @WebParam(name = "metadata", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfKeyValue metadata
    );

    @WebMethod(operationName = "QuerySystemMonitorStateSourcesByTypes", action = "http://videoos.net/2/XProtectCSServerCommand/QuerySystemMonitorStateSourcesByTypes")
    @RequestWrapper(localName = "QuerySystemMonitorStateSourcesByTypes", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.QuerySystemMonitorStateSourcesByTypes")
    @ResponseWrapper(localName = "QuerySystemMonitorStateSourcesByTypesResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.QuerySystemMonitorStateSourcesByTypesResponse")
    @WebResult(name = "QuerySystemMonitorStateSourcesByTypesResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfSystemMonitorStateSource querySystemMonitorStateSourcesByTypes(
        @WebParam(name = "types", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfString types
    );

    @WebMethod(operationName = "SetViewGroupData", action = "http://videoos.net/2/XProtectCSServerCommand/SetViewGroupData")
    @RequestWrapper(localName = "SetViewGroupData", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.SetViewGroupData")
    @ResponseWrapper(localName = "SetViewGroupDataResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.SetViewGroupDataResponse")
    @WebResult(name = "SetViewGroupDataResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.SetViewGroupDataResultType setViewGroupData(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "viewGroupId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String viewGroupId,
        @WebParam(name = "viewGroupdata", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ViewGroupData viewGroupdata
    );

    @WebMethod(operationName = "GetDevicesDisabled", action = "http://videoos.net/2/XProtectCSServerCommand/GetDevicesDisabled")
    @RequestWrapper(localName = "GetDevicesDisabled", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetDevicesDisabled")
    @ResponseWrapper(localName = "GetDevicesDisabledResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetDevicesDisabledResponse")
    @WebResult(name = "GetDevicesDisabledResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ArrayOfDeviceDisabledInfo getDevicesDisabled(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token
    );

    @WebMethod(operationName = "BookmarkDelete", action = "http://videoos.net/2/XProtectCSServerCommand/BookmarkDelete")
    @RequestWrapper(localName = "BookmarkDelete", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkDelete")
    @ResponseWrapper(localName = "BookmarkDeleteResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkDeleteResponse")
    public void bookmarkDelete(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "bookmarkId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String bookmarkId
    );

    @WebMethod(operationName = "OrderPresets", action = "http://videoos.net/2/XProtectCSServerCommand/OrderPreset")
    @RequestWrapper(localName = "OrderPresets", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.OrderPresets")
    @ResponseWrapper(localName = "OrderPresetsResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.OrderPresetsResponse")
    public void orderPresets(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String deviceId,
        @WebParam(name = "ids", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        com.mile.ServerCommandService.ArrayOfGuid ids
    );

    @WebMethod(operationName = "BookmarkGet", action = "http://videoos.net/2/XProtectCSServerCommand/BookmarkGet")
    @RequestWrapper(localName = "BookmarkGet", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkGet")
    @ResponseWrapper(localName = "BookmarkGetResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.BookmarkGetResponse")
    @WebResult(name = "BookmarkGetResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.Bookmark bookmarkGet(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "bookmarkId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String bookmarkId
    );

    @WebMethod(operationName = "GetUserInfo", action = "http://videoos.net/2/XProtectCSServerCommand/GetUserInfo")
    @RequestWrapper(localName = "GetUserInfo", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetUserInfo")
    @ResponseWrapper(localName = "GetUserInfoResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetUserInfoResponse")
    @WebResult(name = "GetUserInfoResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.UserInfo getUserInfo(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token
    );

    @WebMethod(operationName = "GetConfiguration", action = "http://videoos.net/2/XProtectCSServerCommand/GetConfiguration")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.GetConfigurationResponse")
    @WebResult(name = "GetConfigurationResult", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
    public com.mile.ServerCommandService.ConfigurationInfo getConfiguration(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token
    );

    @WebMethod(operationName = "DeletePreset", action = "http://videoos.net/2/XProtectCSServerCommand/DeletePreset")
    @RequestWrapper(localName = "DeletePreset", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.DeletePreset")
    @ResponseWrapper(localName = "DeletePresetResponse", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand", className = "com.mile.ServerCommandService.DeletePresetResponse")
    public void deletePreset(
        @WebParam(name = "token", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String token,
        @WebParam(name = "id", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String id,
        @WebParam(name = "deviceId", targetNamespace = "http://videoos.net/2/XProtectCSServerCommand")
        java.lang.String deviceId
    );
}
