
package com.mile.ServerCommandService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-13T12:46:27.252-04:00
 * Generated source version: 2.4.2
 * 
 */
public final class ServerCommandServiceSoap_ServerCommandServiceSoap1_Client {

    private static final QName SERVICE_NAME = new QName("http://videoos.net/2/XProtectCSServerCommand", "ServerCommandService");

    private ServerCommandServiceSoap_ServerCommandServiceSoap1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServerCommandService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServerCommandService ss = new ServerCommandService(wsdlURL, SERVICE_NAME);
        ServerCommandServiceSoap port = ss.getServerCommandServiceSoap1();  
        
        {
        System.out.println("Invoking setCustomSettingDataGlobal...");
        java.lang.String _setCustomSettingDataGlobal_token = "_setCustomSettingDataGlobal_token370946052";
        java.lang.String _setCustomSettingDataGlobal_customSettingId = "_setCustomSettingDataGlobal_customSettingId1877094640";
        com.mile.ServerCommandService.CustomSettingData _setCustomSettingDataGlobal_customSettingData = new com.mile.ServerCommandService.CustomSettingData();
        _setCustomSettingDataGlobal_customSettingData.setDataVersion(-1267270809);
        com.mile.ServerCommandService.CustomSettingData.CustomSettingDataXml _setCustomSettingDataGlobal_customSettingDataCustomSettingDataXml = new com.mile.ServerCommandService.CustomSettingData.CustomSettingDataXml();
        java.util.List<java.lang.Object> _setCustomSettingDataGlobal_customSettingDataCustomSettingDataXmlContent = new java.util.ArrayList<java.lang.Object>();
        java.lang.Object _setCustomSettingDataGlobal_customSettingDataCustomSettingDataXmlContentVal1 = null;
        _setCustomSettingDataGlobal_customSettingDataCustomSettingDataXmlContent.add(_setCustomSettingDataGlobal_customSettingDataCustomSettingDataXmlContentVal1);
        _setCustomSettingDataGlobal_customSettingDataCustomSettingDataXml.getContent().addAll(_setCustomSettingDataGlobal_customSettingDataCustomSettingDataXmlContent);
        _setCustomSettingDataGlobal_customSettingData.setCustomSettingDataXml(_setCustomSettingDataGlobal_customSettingDataCustomSettingDataXml);
        boolean _setCustomSettingDataGlobal_forceOverride = true;
        com.mile.ServerCommandService.SetCustomSettingResultType _setCustomSettingDataGlobal__return = port.setCustomSettingDataGlobal(_setCustomSettingDataGlobal_token, _setCustomSettingDataGlobal_customSettingId, _setCustomSettingDataGlobal_customSettingData, _setCustomSettingDataGlobal_forceOverride);
        System.out.println("setCustomSettingDataGlobal.result=" + _setCustomSettingDataGlobal__return);


        }
        {
        System.out.println("Invoking setCustomSettingDataUser...");
        java.lang.String _setCustomSettingDataUser_token = "_setCustomSettingDataUser_token108473925";
        java.lang.String _setCustomSettingDataUser_customSettingId = "_setCustomSettingDataUser_customSettingId-1718960729";
        com.mile.ServerCommandService.CustomSettingData _setCustomSettingDataUser_customSettingData = new com.mile.ServerCommandService.CustomSettingData();
        _setCustomSettingDataUser_customSettingData.setDataVersion(-1828954139);
        com.mile.ServerCommandService.CustomSettingData.CustomSettingDataXml _setCustomSettingDataUser_customSettingDataCustomSettingDataXml = new com.mile.ServerCommandService.CustomSettingData.CustomSettingDataXml();
        java.util.List<java.lang.Object> _setCustomSettingDataUser_customSettingDataCustomSettingDataXmlContent = new java.util.ArrayList<java.lang.Object>();
        java.lang.Object _setCustomSettingDataUser_customSettingDataCustomSettingDataXmlContentVal1 = null;
        _setCustomSettingDataUser_customSettingDataCustomSettingDataXmlContent.add(_setCustomSettingDataUser_customSettingDataCustomSettingDataXmlContentVal1);
        _setCustomSettingDataUser_customSettingDataCustomSettingDataXml.getContent().addAll(_setCustomSettingDataUser_customSettingDataCustomSettingDataXmlContent);
        _setCustomSettingDataUser_customSettingData.setCustomSettingDataXml(_setCustomSettingDataUser_customSettingDataCustomSettingDataXml);
        boolean _setCustomSettingDataUser_forceOverride = true;
        com.mile.ServerCommandService.SetCustomSettingResultType _setCustomSettingDataUser__return = port.setCustomSettingDataUser(_setCustomSettingDataUser_token, _setCustomSettingDataUser_customSettingId, _setCustomSettingDataUser_customSettingData, _setCustomSettingDataUser_forceOverride);
        System.out.println("setCustomSettingDataUser.result=" + _setCustomSettingDataUser__return);


        }
        {
        System.out.println("Invoking getServerVersion...");
        java.lang.String _getServerVersion__return = port.getServerVersion();
        System.out.println("getServerVersion.result=" + _getServerVersion__return);


        }
        {
        System.out.println("Invoking getViewGroupData...");
        java.lang.String _getViewGroupData_token = "_getViewGroupData_token-841733296";
        java.lang.String _getViewGroupData_viewGroupId = "_getViewGroupData_viewGroupId-1211518747";
        com.mile.ServerCommandService.ViewGroup _getViewGroupData__return = port.getViewGroupData(_getViewGroupData_token, _getViewGroupData_viewGroupId);
        System.out.println("getViewGroupData.result=" + _getViewGroupData__return);


        }
        {
        System.out.println("Invoking markedDataCreate...");
        java.lang.String _markedDataCreate_token = "_markedDataCreate_token80780976";
        java.lang.String _markedDataCreate_markedDataId = "_markedDataCreate_markedDataId1536422136";
        com.mile.ServerCommandService.ArrayOfGuid _markedDataCreate_deviceIds = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _markedDataCreate_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _markedDataCreate_deviceIdsGuidVal1 = "_markedDataCreate_deviceIdsGuidVal320989559";
        _markedDataCreate_deviceIdsGuid.add(_markedDataCreate_deviceIdsGuidVal1);
        _markedDataCreate_deviceIds.getGuid().addAll(_markedDataCreate_deviceIdsGuid);
        javax.xml.datatype.XMLGregorianCalendar _markedDataCreate_timeStart = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.280-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataCreate_timeTag = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.281-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataCreate_timeEnd = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.282-04:00");
        java.lang.String _markedDataCreate_reference = "_markedDataCreate_reference2098307686";
        java.lang.String _markedDataCreate_header = "_markedDataCreate_header1905797128";
        java.lang.String _markedDataCreate_description = "_markedDataCreate_description2042416983";
        int _markedDataCreate_markedDataType = 153124072;
        boolean _markedDataCreate_useRetention = false;
        javax.xml.datatype.XMLGregorianCalendar _markedDataCreate_retentionExpire = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.283-04:00");
        com.mile.ServerCommandService.RetentionOption _markedDataCreate_retentionOption = new com.mile.ServerCommandService.RetentionOption();
        _markedDataCreate_retentionOption.setRetentionUnits(964459210);
        com.mile.ServerCommandService.RetentionOptionType _markedDataCreate_retentionOptionRetentionOptionType = com.mile.ServerCommandService.RetentionOptionType.UNUSED;
        _markedDataCreate_retentionOption.setRetentionOptionType(_markedDataCreate_retentionOptionRetentionOptionType);
        com.mile.ServerCommandService.MarkedDataResult _markedDataCreate__return = port.markedDataCreate(_markedDataCreate_token, _markedDataCreate_markedDataId, _markedDataCreate_deviceIds, _markedDataCreate_timeStart, _markedDataCreate_timeTag, _markedDataCreate_timeEnd, _markedDataCreate_reference, _markedDataCreate_header, _markedDataCreate_description, _markedDataCreate_markedDataType, _markedDataCreate_useRetention, _markedDataCreate_retentionExpire, _markedDataCreate_retentionOption);
        System.out.println("markedDataCreate.result=" + _markedDataCreate__return);


        }
        {
        System.out.println("Invoking matrixMonitorActivateCamera...");
        java.lang.String _matrixMonitorActivateCamera_token = "_matrixMonitorActivateCamera_token-1494415366";
        java.lang.String _matrixMonitorActivateCamera_matrixMonitorId = "_matrixMonitorActivateCamera_matrixMonitorId1373221862";
        java.lang.String _matrixMonitorActivateCamera_deviceId = "_matrixMonitorActivateCamera_deviceId190294754";
        port.matrixMonitorActivateCamera(_matrixMonitorActivateCamera_token, _matrixMonitorActivateCamera_matrixMonitorId, _matrixMonitorActivateCamera_deviceId);


        }
        {
        System.out.println("Invoking updatePresetPosition...");
        java.lang.String _updatePresetPosition_token = "_updatePresetPosition_token1053647083";
        java.lang.String _updatePresetPosition_id = "_updatePresetPosition_id-1365481271";
        java.lang.String _updatePresetPosition_deviceId = "_updatePresetPosition_deviceId-1642723408";
        port.updatePresetPosition(_updatePresetPosition_token, _updatePresetPosition_id, _updatePresetPosition_deviceId);


        }
        {
        System.out.println("Invoking getCustomSettingDataUser...");
        java.lang.String _getCustomSettingDataUser_token = "_getCustomSettingDataUser_token-865248514";
        java.lang.String _getCustomSettingDataUser_customSettingId = "_getCustomSettingDataUser_customSettingId1966551988";
        com.mile.ServerCommandService.CustomSetting _getCustomSettingDataUser__return = port.getCustomSettingDataUser(_getCustomSettingDataUser_token, _getCustomSettingDataUser_customSettingId);
        System.out.println("getCustomSettingDataUser.result=" + _getCustomSettingDataUser__return);


        }
        {
        System.out.println("Invoking getVersion...");
        int _getVersion__return = port.getVersion();
        System.out.println("getVersion.result=" + _getVersion__return);


        }
        {
        System.out.println("Invoking logout...");
        java.lang.String _logout_instanceId = "_logout_instanceId626699268";
        java.lang.String _logout_currentToken = "_logout_currentToken1225850265";
        port.logout(_logout_instanceId, _logout_currentToken);


        }
        {
        System.out.println("Invoking markedDataSearch...");
        java.lang.String _markedDataSearch_token = "_markedDataSearch_token927800707";
        com.mile.ServerCommandService.ArrayOfGuid _markedDataSearch_deviceIds = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _markedDataSearch_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _markedDataSearch_deviceIdsGuidVal1 = "_markedDataSearch_deviceIdsGuidVal-1820438747";
        _markedDataSearch_deviceIdsGuid.add(_markedDataSearch_deviceIdsGuidVal1);
        _markedDataSearch_deviceIds.getGuid().addAll(_markedDataSearch_deviceIdsGuid);
        java.lang.String _markedDataSearch_searchText = "_markedDataSearch_searchText1099847940";
        com.mile.ServerCommandService.ArrayOfString _markedDataSearch_users = new com.mile.ServerCommandService.ArrayOfString();
        java.util.List<java.lang.String> _markedDataSearch_usersString = new java.util.ArrayList<java.lang.String>();
        java.lang.String _markedDataSearch_usersStringVal1 = "_markedDataSearch_usersStringVal58896006";
        _markedDataSearch_usersString.add(_markedDataSearch_usersStringVal1);
        _markedDataSearch_users.getString().addAll(_markedDataSearch_usersString);
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_createdFromTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.297-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_createdToTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.298-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_markedDataFromTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.298-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_markedDataToTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.333-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_tagTimeFromTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.333-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_tagTimeToTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.336-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_retentionExpireFrom = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.337-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataSearch_retentionExpireTo = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.337-04:00");
        int _markedDataSearch_pageIndex = -2134544188;
        int _markedDataSearch_pageSize = 2097111178;
        com.mile.ServerCommandService.SortOrderOption _markedDataSearch_sortOrder = com.mile.ServerCommandService.SortOrderOption.DESCRIPTION;
        boolean _markedDataSearch_sortAscending = true;
        com.mile.ServerCommandService.ArrayOfMarkedData _markedDataSearch__return = port.markedDataSearch(_markedDataSearch_token, _markedDataSearch_deviceIds, _markedDataSearch_searchText, _markedDataSearch_users, _markedDataSearch_createdFromTime, _markedDataSearch_createdToTime, _markedDataSearch_markedDataFromTime, _markedDataSearch_markedDataToTime, _markedDataSearch_tagTimeFromTime, _markedDataSearch_tagTimeToTime, _markedDataSearch_retentionExpireFrom, _markedDataSearch_retentionExpireTo, _markedDataSearch_pageIndex, _markedDataSearch_pageSize, _markedDataSearch_sortOrder, _markedDataSearch_sortAscending);
        System.out.println("markedDataSearch.result=" + _markedDataSearch__return);


        }
        {
        System.out.println("Invoking bookmarkCreate...");
        java.lang.String _bookmarkCreate_token = "_bookmarkCreate_token-57816463";
        java.lang.String _bookmarkCreate_deviceId = "_bookmarkCreate_deviceId1909914683";
        javax.xml.datatype.XMLGregorianCalendar _bookmarkCreate_timeBegin = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.340-04:00");
        javax.xml.datatype.XMLGregorianCalendar _bookmarkCreate_timeTrigged = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.341-04:00");
        javax.xml.datatype.XMLGregorianCalendar _bookmarkCreate_timeEnd = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.350-04:00");
        java.lang.String _bookmarkCreate_reference = "_bookmarkCreate_reference-1328083903";
        java.lang.String _bookmarkCreate_header = "_bookmarkCreate_header-1611357781";
        java.lang.String _bookmarkCreate_description = "_bookmarkCreate_description180446797";
        com.mile.ServerCommandService.Bookmark _bookmarkCreate__return = port.bookmarkCreate(_bookmarkCreate_token, _bookmarkCreate_deviceId, _bookmarkCreate_timeBegin, _bookmarkCreate_timeTrigged, _bookmarkCreate_timeEnd, _bookmarkCreate_reference, _bookmarkCreate_header, _bookmarkCreate_description);
        System.out.println("bookmarkCreate.result=" + _bookmarkCreate__return);


        }
        {
        System.out.println("Invoking getVmoServicesList...");
        com.mile.ServerCommandService.ArrayOfDictionaryEntry _getVmoServicesList__return = port.getVmoServicesList();
        System.out.println("getVmoServicesList.result=" + _getVmoServicesList__return);


        }
        {
        System.out.println("Invoking markedDataUpdate...");
        java.lang.String _markedDataUpdate_token = "_markedDataUpdate_token668031046";
        java.lang.String _markedDataUpdate_markedDataId = "_markedDataUpdate_markedDataId938763441";
        com.mile.ServerCommandService.ArrayOfGuid _markedDataUpdate_deviceIds = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _markedDataUpdate_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _markedDataUpdate_deviceIdsGuidVal1 = "_markedDataUpdate_deviceIdsGuidVal1708841379";
        _markedDataUpdate_deviceIdsGuid.add(_markedDataUpdate_deviceIdsGuidVal1);
        _markedDataUpdate_deviceIds.getGuid().addAll(_markedDataUpdate_deviceIdsGuid);
        javax.xml.datatype.XMLGregorianCalendar _markedDataUpdate_timeStart = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.352-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataUpdate_timeTag = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.353-04:00");
        javax.xml.datatype.XMLGregorianCalendar _markedDataUpdate_timeEnd = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.353-04:00");
        java.lang.String _markedDataUpdate_reference = "_markedDataUpdate_reference-1565799389";
        java.lang.String _markedDataUpdate_header = "_markedDataUpdate_header-1194816181";
        java.lang.String _markedDataUpdate_description = "_markedDataUpdate_description-903343049";
        int _markedDataUpdate_markedDataType = 13841129;
        boolean _markedDataUpdate_useRetention = true;
        javax.xml.datatype.XMLGregorianCalendar _markedDataUpdate_retentionExpire = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.354-04:00");
        com.mile.ServerCommandService.RetentionOption _markedDataUpdate_retentionOption = new com.mile.ServerCommandService.RetentionOption();
        _markedDataUpdate_retentionOption.setRetentionUnits(-1809088089);
        com.mile.ServerCommandService.RetentionOptionType _markedDataUpdate_retentionOptionRetentionOptionType = com.mile.ServerCommandService.RetentionOptionType.INDEFINITE;
        _markedDataUpdate_retentionOption.setRetentionOptionType(_markedDataUpdate_retentionOptionRetentionOptionType);
        com.mile.ServerCommandService.MarkedDataResult _markedDataUpdate__return = port.markedDataUpdate(_markedDataUpdate_token, _markedDataUpdate_markedDataId, _markedDataUpdate_deviceIds, _markedDataUpdate_timeStart, _markedDataUpdate_timeTag, _markedDataUpdate_timeEnd, _markedDataUpdate_reference, _markedDataUpdate_header, _markedDataUpdate_description, _markedDataUpdate_markedDataType, _markedDataUpdate_useRetention, _markedDataUpdate_retentionExpire, _markedDataUpdate_retentionOption);
        System.out.println("markedDataUpdate.result=" + _markedDataUpdate__return);


        }
        {
        System.out.println("Invoking checkSmartClientVersion...");
        int _checkSmartClientVersion_major = 641155757;
        int _checkSmartClientVersion_minor = -524511353;
        java.lang.String _checkSmartClientVersion_revision = "_checkSmartClientVersion_revision-1067064619";
        com.mile.ServerCommandService.SmartClientVersion _checkSmartClientVersion__return = port.checkSmartClientVersion(_checkSmartClientVersion_major, _checkSmartClientVersion_minor, _checkSmartClientVersion_revision);
        System.out.println("checkSmartClientVersion.result=" + _checkSmartClientVersion__return);


        }
        {
        System.out.println("Invoking getConfigurationHardware...");
        java.lang.String _getConfigurationHardware_token = "_getConfigurationHardware_token-1256479691";
        com.mile.ServerCommandService.ArrayOfGuid _getConfigurationHardware_hardwareIds = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _getConfigurationHardware_hardwareIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getConfigurationHardware_hardwareIdsGuidVal1 = "_getConfigurationHardware_hardwareIdsGuidVal1227716621";
        _getConfigurationHardware_hardwareIdsGuid.add(_getConfigurationHardware_hardwareIdsGuidVal1);
        _getConfigurationHardware_hardwareIds.getGuid().addAll(_getConfigurationHardware_hardwareIdsGuid);
        com.mile.ServerCommandService.ArrayOfHardwareInfo _getConfigurationHardware__return = port.getConfigurationHardware(_getConfigurationHardware_token, _getConfigurationHardware_hardwareIds);
        System.out.println("getConfigurationHardware.result=" + _getConfigurationHardware__return);


        }
        {
        System.out.println("Invoking getViewGroups...");
        java.lang.String _getViewGroups_token = "_getViewGroups_token476517346";
        com.mile.ServerCommandService.ArrayOfViewGroupInfo _getViewGroups__return = port.getViewGroups(_getViewGroups_token);
        System.out.println("getViewGroups.result=" + _getViewGroups__return);


        }
        {
        System.out.println("Invoking bookmarkGetNewReference...");
        java.lang.String _bookmarkGetNewReference_token = "_bookmarkGetNewReference_token562286864";
        java.lang.String _bookmarkGetNewReference_deviceId = "_bookmarkGetNewReference_deviceId190573771";
        boolean _bookmarkGetNewReference_live = true;
        com.mile.ServerCommandService.BookmarkReference _bookmarkGetNewReference__return = port.bookmarkGetNewReference(_bookmarkGetNewReference_token, _bookmarkGetNewReference_deviceId, _bookmarkGetNewReference_live);
        System.out.println("bookmarkGetNewReference.result=" + _bookmarkGetNewReference__return);


        }
        {
        System.out.println("Invoking getPresets...");
        java.lang.String _getPresets_token = "_getPresets_token-2118756740";
        java.lang.String _getPresets_deviceId = "_getPresets_deviceId-1561190085";
        com.mile.ServerCommandService.ArrayOfPresetInfo _getPresets__return = port.getPresets(_getPresets_token, _getPresets_deviceId);
        System.out.println("getPresets.result=" + _getPresets__return);


        }
        {
        System.out.println("Invoking bookmarkSearchTime...");
        java.lang.String _bookmarkSearchTime_token = "_bookmarkSearchTime_token-217600099";
        javax.xml.datatype.XMLGregorianCalendar _bookmarkSearchTime_time = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.365-04:00");
        com.mile.ServerCommandService.TimeDuration _bookmarkSearchTime_timeLimit = new com.mile.ServerCommandService.TimeDuration();
        _bookmarkSearchTime_timeLimit.setMicroSeconds(-1583781181767581104l);
        int _bookmarkSearchTime_countLimit = -1528407803;
        com.mile.ServerCommandService.ArrayOfMediaDeviceType _bookmarkSearchTime_deviceTypes = new com.mile.ServerCommandService.ArrayOfMediaDeviceType();
        java.util.List<com.mile.ServerCommandService.MediaDeviceType> _bookmarkSearchTime_deviceTypesMediaDeviceType = new java.util.ArrayList<com.mile.ServerCommandService.MediaDeviceType>();
        com.mile.ServerCommandService.MediaDeviceType _bookmarkSearchTime_deviceTypesMediaDeviceTypeVal1 = com.mile.ServerCommandService.MediaDeviceType.MICROPHONE;
        _bookmarkSearchTime_deviceTypesMediaDeviceType.add(_bookmarkSearchTime_deviceTypesMediaDeviceTypeVal1);
        _bookmarkSearchTime_deviceTypes.getMediaDeviceType().addAll(_bookmarkSearchTime_deviceTypesMediaDeviceType);
        com.mile.ServerCommandService.ArrayOfGuid _bookmarkSearchTime_optDeviceIds = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _bookmarkSearchTime_optDeviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _bookmarkSearchTime_optDeviceIdsGuidVal1 = "_bookmarkSearchTime_optDeviceIdsGuidVal11183815";
        _bookmarkSearchTime_optDeviceIdsGuid.add(_bookmarkSearchTime_optDeviceIdsGuidVal1);
        _bookmarkSearchTime_optDeviceIds.getGuid().addAll(_bookmarkSearchTime_optDeviceIdsGuid);
        com.mile.ServerCommandService.ArrayOfString _bookmarkSearchTime_optUsers = new com.mile.ServerCommandService.ArrayOfString();
        java.util.List<java.lang.String> _bookmarkSearchTime_optUsersString = new java.util.ArrayList<java.lang.String>();
        java.lang.String _bookmarkSearchTime_optUsersStringVal1 = "_bookmarkSearchTime_optUsersStringVal606999129";
        _bookmarkSearchTime_optUsersString.add(_bookmarkSearchTime_optUsersStringVal1);
        _bookmarkSearchTime_optUsers.getString().addAll(_bookmarkSearchTime_optUsersString);
        java.lang.String _bookmarkSearchTime_optSearchStr = "_bookmarkSearchTime_optSearchStr-385365688";
        com.mile.ServerCommandService.ArrayOfBookmark _bookmarkSearchTime__return = port.bookmarkSearchTime(_bookmarkSearchTime_token, _bookmarkSearchTime_time, _bookmarkSearchTime_timeLimit, _bookmarkSearchTime_countLimit, _bookmarkSearchTime_deviceTypes, _bookmarkSearchTime_optDeviceIds, _bookmarkSearchTime_optUsers, _bookmarkSearchTime_optSearchStr);
        System.out.println("bookmarkSearchTime.result=" + _bookmarkSearchTime__return);


        }
        {
        System.out.println("Invoking markedDataGetNewReference...");
        java.lang.String _markedDataGetNewReference_token = "_markedDataGetNewReference_token1638291555";
        com.mile.ServerCommandService.ArrayOfGuid _markedDataGetNewReference_deviceIds = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _markedDataGetNewReference_deviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _markedDataGetNewReference_deviceIdsGuidVal1 = "_markedDataGetNewReference_deviceIdsGuidVal-179485616";
        _markedDataGetNewReference_deviceIdsGuid.add(_markedDataGetNewReference_deviceIdsGuidVal1);
        _markedDataGetNewReference_deviceIds.getGuid().addAll(_markedDataGetNewReference_deviceIdsGuid);
        boolean _markedDataGetNewReference_live = false;
        com.mile.ServerCommandService.MarkedDataReference _markedDataGetNewReference__return = port.markedDataGetNewReference(_markedDataGetNewReference_token, _markedDataGetNewReference_deviceIds, _markedDataGetNewReference_live);
        System.out.println("markedDataGetNewReference.result=" + _markedDataGetNewReference__return);


        }
        {
        System.out.println("Invoking getClientProfile...");
        java.lang.String _getClientProfile_token = "_getClientProfile_token262498994";
        boolean _getClientProfile_withSetting = true;
        com.mile.ServerCommandService.ClientProfile _getClientProfile__return = port.getClientProfile(_getClientProfile_token, _getClientProfile_withSetting);
        System.out.println("getClientProfile.result=" + _getClientProfile__return);


        }
        {
        System.out.println("Invoking bookmarkUpdate...");
        java.lang.String _bookmarkUpdate_token = "_bookmarkUpdate_token1987405729";
        java.lang.String _bookmarkUpdate_bookmarkId = "_bookmarkUpdate_bookmarkId-1295995291";
        java.lang.String _bookmarkUpdate_deviceId = "_bookmarkUpdate_deviceId224026790";
        javax.xml.datatype.XMLGregorianCalendar _bookmarkUpdate_timeBegin = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.375-04:00");
        javax.xml.datatype.XMLGregorianCalendar _bookmarkUpdate_timeTrigged = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.376-04:00");
        javax.xml.datatype.XMLGregorianCalendar _bookmarkUpdate_timeEnd = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.376-04:00");
        java.lang.String _bookmarkUpdate_reference = "_bookmarkUpdate_reference-1477595758";
        java.lang.String _bookmarkUpdate_header = "_bookmarkUpdate_header-387187811";
        java.lang.String _bookmarkUpdate_description = "_bookmarkUpdate_description2030784237";
        com.mile.ServerCommandService.Bookmark _bookmarkUpdate__return = port.bookmarkUpdate(_bookmarkUpdate_token, _bookmarkUpdate_bookmarkId, _bookmarkUpdate_deviceId, _bookmarkUpdate_timeBegin, _bookmarkUpdate_timeTrigged, _bookmarkUpdate_timeEnd, _bookmarkUpdate_reference, _bookmarkUpdate_header, _bookmarkUpdate_description);
        System.out.println("bookmarkUpdate.result=" + _bookmarkUpdate__return);


        }
        {
        System.out.println("Invoking getProductInfo...");
        com.mile.ServerCommandService.ProductInfo _getProductInfo__return = port.getProductInfo();
        System.out.println("getProductInfo.result=" + _getProductInfo__return);


        }
        {
        System.out.println("Invoking createPreset...");
        java.lang.String _createPreset_token = "_createPreset_token-2101524892";
        java.lang.String _createPreset_deviceId = "_createPreset_deviceId-1171694011";
        java.lang.String _createPreset_name = "_createPreset_name1965333031";
        java.lang.String _createPreset__return = port.createPreset(_createPreset_token, _createPreset_deviceId, _createPreset_name);
        System.out.println("createPreset.result=" + _createPreset__return);


        }
        {
        System.out.println("Invoking isOnline...");
        boolean _isOnline__return = port.isOnline();
        System.out.println("isOnline.result=" + _isOnline__return);


        }
        {
        System.out.println("Invoking queryRecorderInfo...");
        java.lang.String _queryRecorderInfo_token = "_queryRecorderInfo_token-776949156";
        java.lang.String _queryRecorderInfo_recorderId = "_queryRecorderInfo_recorderId-1697338778";
        com.mile.ServerCommandService.RecorderInfo _queryRecorderInfo__return = port.queryRecorderInfo(_queryRecorderInfo_token, _queryRecorderInfo_recorderId);
        System.out.println("queryRecorderInfo.result=" + _queryRecorderInfo__return);


        }
        {
        System.out.println("Invoking getCustomSettingDataGlobal...");
        java.lang.String _getCustomSettingDataGlobal_token = "_getCustomSettingDataGlobal_token1169209799";
        java.lang.String _getCustomSettingDataGlobal_customSettingId = "_getCustomSettingDataGlobal_customSettingId1733693484";
        com.mile.ServerCommandService.CustomSetting _getCustomSettingDataGlobal__return = port.getCustomSettingDataGlobal(_getCustomSettingDataGlobal_token, _getCustomSettingDataGlobal_customSettingId);
        System.out.println("getCustomSettingDataGlobal.result=" + _getCustomSettingDataGlobal__return);


        }
        {
        System.out.println("Invoking getConfigurationRecorders...");
        java.lang.String _getConfigurationRecorders_token = "_getConfigurationRecorders_token-199574731";
        com.mile.ServerCommandService.ArrayOfGuid _getConfigurationRecorders_recorderIds = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _getConfigurationRecorders_recorderIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getConfigurationRecorders_recorderIdsGuidVal1 = "_getConfigurationRecorders_recorderIdsGuidVal-1144169459";
        _getConfigurationRecorders_recorderIdsGuid.add(_getConfigurationRecorders_recorderIdsGuidVal1);
        _getConfigurationRecorders_recorderIds.getGuid().addAll(_getConfigurationRecorders_recorderIdsGuid);
        com.mile.ServerCommandService.ArrayOfRecorderInfo _getConfigurationRecorders__return = port.getConfigurationRecorders(_getConfigurationRecorders_token, _getConfigurationRecorders_recorderIds);
        System.out.println("getConfigurationRecorders.result=" + _getConfigurationRecorders__return);


        }
        {
        System.out.println("Invoking getSystemLicenseInfo...");
        com.mile.ServerCommandService.SystemLicenseInfo _getSystemLicenseInfo__return = port.getSystemLicenseInfo();
        System.out.println("getSystemLicenseInfo.result=" + _getSystemLicenseInfo__return);


        }
        {
        System.out.println("Invoking alertsGetAroundWithSpan...");
        java.lang.String _alertsGetAroundWithSpan_token = "_alertsGetAroundWithSpan_token2136883901";
        com.mile.ServerCommandService.ArrayOfGuid _alertsGetAroundWithSpan_alertIds = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _alertsGetAroundWithSpan_alertIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _alertsGetAroundWithSpan_alertIdsGuidVal1 = "_alertsGetAroundWithSpan_alertIdsGuidVal919117287";
        _alertsGetAroundWithSpan_alertIdsGuid.add(_alertsGetAroundWithSpan_alertIdsGuidVal1);
        _alertsGetAroundWithSpan_alertIds.getGuid().addAll(_alertsGetAroundWithSpan_alertIdsGuid);
        javax.xml.datatype.XMLGregorianCalendar _alertsGetAroundWithSpan_centerTime = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.396-04:00");
        com.mile.ServerCommandService.TimeDuration _alertsGetAroundWithSpan_maxTimeBefore = new com.mile.ServerCommandService.TimeDuration();
        _alertsGetAroundWithSpan_maxTimeBefore.setMicroSeconds(-4214554579706744963l);
        int _alertsGetAroundWithSpan_maxCountBefore = 937681332;
        com.mile.ServerCommandService.TimeDuration _alertsGetAroundWithSpan_maxTimeAfter = new com.mile.ServerCommandService.TimeDuration();
        _alertsGetAroundWithSpan_maxTimeAfter.setMicroSeconds(-5507489620584131531l);
        int _alertsGetAroundWithSpan_maxCountAfter = -1027007548;
        com.mile.ServerCommandService.ArrayOfAlertOccurrence _alertsGetAroundWithSpan__return = port.alertsGetAroundWithSpan(_alertsGetAroundWithSpan_token, _alertsGetAroundWithSpan_alertIds, _alertsGetAroundWithSpan_centerTime, _alertsGetAroundWithSpan_maxTimeBefore, _alertsGetAroundWithSpan_maxCountBefore, _alertsGetAroundWithSpan_maxTimeAfter, _alertsGetAroundWithSpan_maxCountAfter);
        System.out.println("alertsGetAroundWithSpan.result=" + _alertsGetAroundWithSpan__return);


        }
        {
        System.out.println("Invoking queryChanges...");
        java.lang.String _queryChanges_token = "_queryChanges_token954847862";
        javax.xml.datatype.XMLGregorianCalendar _queryChanges_changesFrom = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-13T12:46:27.397-04:00");
        com.mile.ServerCommandService.ArrayOfChange _queryChanges__return = port.queryChanges(_queryChanges_token, _queryChanges_changesFrom);
        System.out.println("queryChanges.result=" + _queryChanges__return);


        }
        {
        System.out.println("Invoking querySystemMonitorStateSourcesByIds...");
        com.mile.ServerCommandService.ArrayOfString _querySystemMonitorStateSourcesByIds_ids = new com.mile.ServerCommandService.ArrayOfString();
        java.util.List<java.lang.String> _querySystemMonitorStateSourcesByIds_idsString = new java.util.ArrayList<java.lang.String>();
        java.lang.String _querySystemMonitorStateSourcesByIds_idsStringVal1 = "_querySystemMonitorStateSourcesByIds_idsStringVal392644916";
        _querySystemMonitorStateSourcesByIds_idsString.add(_querySystemMonitorStateSourcesByIds_idsStringVal1);
        _querySystemMonitorStateSourcesByIds_ids.getString().addAll(_querySystemMonitorStateSourcesByIds_idsString);
        com.mile.ServerCommandService.ArrayOfSystemMonitorStateSource _querySystemMonitorStateSourcesByIds__return = port.querySystemMonitorStateSourcesByIds(_querySystemMonitorStateSourcesByIds_ids);
        System.out.println("querySystemMonitorStateSourcesByIds.result=" + _querySystemMonitorStateSourcesByIds__return);


        }
        {
        System.out.println("Invoking eventTrigger...");
        java.lang.String _eventTrigger_token = "_eventTrigger_token1168356934";
        java.lang.String _eventTrigger_eventId = "_eventTrigger_eventId-2121476287";
        port.eventTrigger(_eventTrigger_token, _eventTrigger_eventId);


        }
        {
        System.out.println("Invoking bookmarkSearchFromBookmark...");
        java.lang.String _bookmarkSearchFromBookmark_token = "_bookmarkSearchFromBookmark_token-996240738";
        java.lang.String _bookmarkSearchFromBookmark_fromBookmarkId = "_bookmarkSearchFromBookmark_fromBookmarkId-290208357";
        com.mile.ServerCommandService.TimeDuration _bookmarkSearchFromBookmark_timeLimit = new com.mile.ServerCommandService.TimeDuration();
        _bookmarkSearchFromBookmark_timeLimit.setMicroSeconds(6918483110631986755l);
        int _bookmarkSearchFromBookmark_countLimit = 1161733486;
        com.mile.ServerCommandService.ArrayOfMediaDeviceType _bookmarkSearchFromBookmark_deviceTypes = new com.mile.ServerCommandService.ArrayOfMediaDeviceType();
        java.util.List<com.mile.ServerCommandService.MediaDeviceType> _bookmarkSearchFromBookmark_deviceTypesMediaDeviceType = new java.util.ArrayList<com.mile.ServerCommandService.MediaDeviceType>();
        com.mile.ServerCommandService.MediaDeviceType _bookmarkSearchFromBookmark_deviceTypesMediaDeviceTypeVal1 = com.mile.ServerCommandService.MediaDeviceType.CAMERA;
        _bookmarkSearchFromBookmark_deviceTypesMediaDeviceType.add(_bookmarkSearchFromBookmark_deviceTypesMediaDeviceTypeVal1);
        _bookmarkSearchFromBookmark_deviceTypes.getMediaDeviceType().addAll(_bookmarkSearchFromBookmark_deviceTypesMediaDeviceType);
        com.mile.ServerCommandService.ArrayOfGuid _bookmarkSearchFromBookmark_optDeviceIds = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _bookmarkSearchFromBookmark_optDeviceIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _bookmarkSearchFromBookmark_optDeviceIdsGuidVal1 = "_bookmarkSearchFromBookmark_optDeviceIdsGuidVal1163885173";
        _bookmarkSearchFromBookmark_optDeviceIdsGuid.add(_bookmarkSearchFromBookmark_optDeviceIdsGuidVal1);
        _bookmarkSearchFromBookmark_optDeviceIds.getGuid().addAll(_bookmarkSearchFromBookmark_optDeviceIdsGuid);
        com.mile.ServerCommandService.ArrayOfString _bookmarkSearchFromBookmark_optUsers = new com.mile.ServerCommandService.ArrayOfString();
        java.util.List<java.lang.String> _bookmarkSearchFromBookmark_optUsersString = new java.util.ArrayList<java.lang.String>();
        java.lang.String _bookmarkSearchFromBookmark_optUsersStringVal1 = "_bookmarkSearchFromBookmark_optUsersStringVal-776187920";
        _bookmarkSearchFromBookmark_optUsersString.add(_bookmarkSearchFromBookmark_optUsersStringVal1);
        _bookmarkSearchFromBookmark_optUsers.getString().addAll(_bookmarkSearchFromBookmark_optUsersString);
        java.lang.String _bookmarkSearchFromBookmark_optSearchStr = "_bookmarkSearchFromBookmark_optSearchStr-1959509792";
        com.mile.ServerCommandService.ArrayOfBookmark _bookmarkSearchFromBookmark__return = port.bookmarkSearchFromBookmark(_bookmarkSearchFromBookmark_token, _bookmarkSearchFromBookmark_fromBookmarkId, _bookmarkSearchFromBookmark_timeLimit, _bookmarkSearchFromBookmark_countLimit, _bookmarkSearchFromBookmark_deviceTypes, _bookmarkSearchFromBookmark_optDeviceIds, _bookmarkSearchFromBookmark_optUsers, _bookmarkSearchFromBookmark_optSearchStr);
        System.out.println("bookmarkSearchFromBookmark.result=" + _bookmarkSearchFromBookmark__return);


        }
        {
        System.out.println("Invoking markedDataDelete...");
        java.lang.String _markedDataDelete_token = "_markedDataDelete_token86870729";
        com.mile.ServerCommandService.ArrayOfGuid _markedDataDelete_markedDataIds = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _markedDataDelete_markedDataIdsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _markedDataDelete_markedDataIdsGuidVal1 = "_markedDataDelete_markedDataIdsGuidVal725312204";
        _markedDataDelete_markedDataIdsGuid.add(_markedDataDelete_markedDataIdsGuidVal1);
        _markedDataDelete_markedDataIds.getGuid().addAll(_markedDataDelete_markedDataIdsGuid);
        com.mile.ServerCommandService.ArrayOfMarkedDataResult _markedDataDelete__return = port.markedDataDelete(_markedDataDelete_token, _markedDataDelete_markedDataIds);
        System.out.println("markedDataDelete.result=" + _markedDataDelete__return);


        }
        {
        System.out.println("Invoking markedDataGet...");
        java.lang.String _markedDataGet_token = "_markedDataGet_token-93377177";
        java.lang.String _markedDataGet_markedDataId = "_markedDataGet_markedDataId-1176750086";
        com.mile.ServerCommandService.MarkedData _markedDataGet__return = port.markedDataGet(_markedDataGet_token, _markedDataGet_markedDataId);
        System.out.println("markedDataGet.result=" + _markedDataGet__return);


        }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_instanceId = "_login_instanceId1873595546";
        java.lang.String _login_currentToken = "_login_currentToken-55086069";
        com.mile.ServerCommandService.LoginInfo _login__return = port.login(_login_instanceId, _login_currentToken);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking getSmartClientVersion...");
        com.mile.ServerCommandService.SmartClientVersion _getSmartClientVersion__return = port.getSmartClientVersion();
        System.out.println("getSmartClientVersion.result=" + _getSmartClientVersion__return);


        }
        {
        System.out.println("Invoking updatePresetName...");
        java.lang.String _updatePresetName_token = "_updatePresetName_token-715454679";
        java.lang.String _updatePresetName_id = "_updatePresetName_id1711191654";
        java.lang.String _updatePresetName_deviceId = "_updatePresetName_deviceId-227229993";
        java.lang.String _updatePresetName_newName = "_updatePresetName_newName-118903779";
        port.updatePresetName(_updatePresetName_token, _updatePresetName_id, _updatePresetName_deviceId, _updatePresetName_newName);


        }
        {
        System.out.println("Invoking eventTriggerWithMetadata...");
        java.lang.String _eventTriggerWithMetadata_token = "_eventTriggerWithMetadata_token-548563788";
        java.lang.String _eventTriggerWithMetadata_eventId = "_eventTriggerWithMetadata_eventId1927258433";
        com.mile.ServerCommandService.ArrayOfKeyValue _eventTriggerWithMetadata_metadata = new com.mile.ServerCommandService.ArrayOfKeyValue();
        java.util.List<com.mile.ServerCommandService.KeyValue> _eventTriggerWithMetadata_metadataKeyValue = new java.util.ArrayList<com.mile.ServerCommandService.KeyValue>();
        com.mile.ServerCommandService.KeyValue _eventTriggerWithMetadata_metadataKeyValueVal1 = new com.mile.ServerCommandService.KeyValue();
        _eventTriggerWithMetadata_metadataKeyValueVal1.setKey("Key-1969345621");
        _eventTriggerWithMetadata_metadataKeyValueVal1.setValue("Value1641918087");
        _eventTriggerWithMetadata_metadataKeyValue.add(_eventTriggerWithMetadata_metadataKeyValueVal1);
        _eventTriggerWithMetadata_metadata.getKeyValue().addAll(_eventTriggerWithMetadata_metadataKeyValue);
        port.eventTriggerWithMetadata(_eventTriggerWithMetadata_token, _eventTriggerWithMetadata_eventId, _eventTriggerWithMetadata_metadata);


        }
        {
        System.out.println("Invoking querySystemMonitorStateSourcesByTypes...");
        com.mile.ServerCommandService.ArrayOfString _querySystemMonitorStateSourcesByTypes_types = new com.mile.ServerCommandService.ArrayOfString();
        java.util.List<java.lang.String> _querySystemMonitorStateSourcesByTypes_typesString = new java.util.ArrayList<java.lang.String>();
        java.lang.String _querySystemMonitorStateSourcesByTypes_typesStringVal1 = "_querySystemMonitorStateSourcesByTypes_typesStringVal-1688145296";
        _querySystemMonitorStateSourcesByTypes_typesString.add(_querySystemMonitorStateSourcesByTypes_typesStringVal1);
        _querySystemMonitorStateSourcesByTypes_types.getString().addAll(_querySystemMonitorStateSourcesByTypes_typesString);
        com.mile.ServerCommandService.ArrayOfSystemMonitorStateSource _querySystemMonitorStateSourcesByTypes__return = port.querySystemMonitorStateSourcesByTypes(_querySystemMonitorStateSourcesByTypes_types);
        System.out.println("querySystemMonitorStateSourcesByTypes.result=" + _querySystemMonitorStateSourcesByTypes__return);


        }
        {
        System.out.println("Invoking setViewGroupData...");
        java.lang.String _setViewGroupData_token = "_setViewGroupData_token78885171";
        java.lang.String _setViewGroupData_viewGroupId = "_setViewGroupData_viewGroupId-2116010444";
        com.mile.ServerCommandService.ViewGroupData _setViewGroupData_viewGroupdata = new com.mile.ServerCommandService.ViewGroupData();
        _setViewGroupData_viewGroupdata.setDataVersion(1495350937);
        _setViewGroupData_viewGroupdata.setXmlVersion(1887855055);
        com.mile.ServerCommandService.ViewGroupData.ViewGroupDataXml _setViewGroupData_viewGroupdataViewGroupDataXml = new com.mile.ServerCommandService.ViewGroupData.ViewGroupDataXml();
        java.util.List<java.lang.Object> _setViewGroupData_viewGroupdataViewGroupDataXmlContent = new java.util.ArrayList<java.lang.Object>();
        java.lang.Object _setViewGroupData_viewGroupdataViewGroupDataXmlContentVal1 = null;
        _setViewGroupData_viewGroupdataViewGroupDataXmlContent.add(_setViewGroupData_viewGroupdataViewGroupDataXmlContentVal1);
        _setViewGroupData_viewGroupdataViewGroupDataXml.getContent().addAll(_setViewGroupData_viewGroupdataViewGroupDataXmlContent);
        _setViewGroupData_viewGroupdata.setViewGroupDataXml(_setViewGroupData_viewGroupdataViewGroupDataXml);
        com.mile.ServerCommandService.SetViewGroupDataResultType _setViewGroupData__return = port.setViewGroupData(_setViewGroupData_token, _setViewGroupData_viewGroupId, _setViewGroupData_viewGroupdata);
        System.out.println("setViewGroupData.result=" + _setViewGroupData__return);


        }
        {
        System.out.println("Invoking getDevicesDisabled...");
        java.lang.String _getDevicesDisabled_token = "_getDevicesDisabled_token-695952961";
        com.mile.ServerCommandService.ArrayOfDeviceDisabledInfo _getDevicesDisabled__return = port.getDevicesDisabled(_getDevicesDisabled_token);
        System.out.println("getDevicesDisabled.result=" + _getDevicesDisabled__return);


        }
        {
        System.out.println("Invoking bookmarkDelete...");
        java.lang.String _bookmarkDelete_token = "_bookmarkDelete_token360364352";
        java.lang.String _bookmarkDelete_bookmarkId = "_bookmarkDelete_bookmarkId-748574496";
        port.bookmarkDelete(_bookmarkDelete_token, _bookmarkDelete_bookmarkId);


        }
        {
        System.out.println("Invoking orderPresets...");
        java.lang.String _orderPresets_token = "_orderPresets_token-1623562322";
        java.lang.String _orderPresets_deviceId = "_orderPresets_deviceId1734332891";
        com.mile.ServerCommandService.ArrayOfGuid _orderPresets_ids = new com.mile.ServerCommandService.ArrayOfGuid();
        java.util.List<java.lang.String> _orderPresets_idsGuid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _orderPresets_idsGuidVal1 = "_orderPresets_idsGuidVal-70887850";
        _orderPresets_idsGuid.add(_orderPresets_idsGuidVal1);
        _orderPresets_ids.getGuid().addAll(_orderPresets_idsGuid);
        port.orderPresets(_orderPresets_token, _orderPresets_deviceId, _orderPresets_ids);


        }
        {
        System.out.println("Invoking bookmarkGet...");
        java.lang.String _bookmarkGet_token = "_bookmarkGet_token1005703134";
        java.lang.String _bookmarkGet_bookmarkId = "_bookmarkGet_bookmarkId519171329";
        com.mile.ServerCommandService.Bookmark _bookmarkGet__return = port.bookmarkGet(_bookmarkGet_token, _bookmarkGet_bookmarkId);
        System.out.println("bookmarkGet.result=" + _bookmarkGet__return);


        }
        {
        System.out.println("Invoking getUserInfo...");
        java.lang.String _getUserInfo_token = "_getUserInfo_token-1672425021";
        com.mile.ServerCommandService.UserInfo _getUserInfo__return = port.getUserInfo(_getUserInfo_token);
        System.out.println("getUserInfo.result=" + _getUserInfo__return);


        }
        {
        System.out.println("Invoking getConfiguration...");
        java.lang.String _getConfiguration_token = "_getConfiguration_token113086717";
        com.mile.ServerCommandService.ConfigurationInfo _getConfiguration__return = port.getConfiguration(_getConfiguration_token);
        System.out.println("getConfiguration.result=" + _getConfiguration__return);


        }
        {
        System.out.println("Invoking deletePreset...");
        java.lang.String _deletePreset_token = "_deletePreset_token-363343876";
        java.lang.String _deletePreset_id = "_deletePreset_id-1448720976";
        java.lang.String _deletePreset_deviceId = "_deletePreset_deviceId-1956586999";
        port.deletePreset(_deletePreset_token, _deletePreset_id, _deletePreset_deviceId);


        }

        System.exit(0);
    }

}
